src/Web/wwwroot/app/vault/vaultAddSiteController.js, src/Web/wwwroot/app/vault/vaultEditSiteController.js, src/Web/wwwroot/app/vault/views/vaultAddSite.html, src/Web/wwwroot/app/vault/views/vaultEditSite.html
Folders should be sorted in alphabetical order when adding or editing a
site.
Code not tested but was used in other parts of the site.
=> Editing or adding a site, folders are not sorted in alphabetical order

entrypoint.sh
Hi,
This PR is related to https://github.com/bitwarden/core/pull/292 and should be merged at the same time.
Thx !
=> Rework service user

Dockerfile
Hi,
This PR is related to https://github.com/bitwarden/core/pull/305
Thank you 👍
=> Add a bitwarden label to docker images

src/app/tools/import.component.html
This goes together with https://github.com/bitwarden/jslib/pull/13.
=> Add instructions for passman

src/app/tools/password-generator.component.html, src/locales/en/messages.json
This is the web adaptation to implement the changes proposed at bitwarden/jslib#12
=> Adapt the interface to use passphrase generation

package-lock.json, package.json, src/app/app.module.ts, src/app/vault/add-edit.component.html, src/scss/styles.scss
Companion pull request for https://github.com/bitwarden/desktop/pull/237
Depends on the jslib pull request https://github.com/bitwarden/jslib/pull/35
=> Drag n drop sorting for custom fields

package.json
- **jslib**: Update from 3d2e2cb -> 3a40cb8
- **package.json**: updated sub:pull script to include target branches
=> Update jslib (3d2e2cb -> 3a40cb8) and npm sub:pull script

src/app/organizations/vault/add-edit.component.ts, src/app/organizations/vault/vault.component.html, src/app/organizations/vault/vault.component.ts, src/app/vault/add-edit.component.html, src/app/vault/ciphers.component.html, src/app/vault/ciphers.component.ts, src/app/vault/vault.component.html, src/app/vault/vault.component.ts, src/locales/en/messages.json
> Add the ability to clone items on the web vault.  
**Personal Vault Context**
Personal items can be cloned 
Allow ownership selection (collections that are "read only" will not be visible)
Restrict organizational item cloning 
**Organizational Vault Context**
Organizational items can be cloned
Allow collections to be chosen during creation (collections that are "read only" will not be visible)
- **Organization: add-edit.component.ts**: Overridden saveCipher method will properly route add/edit call based on admin status
- **Organization: vault.component.html**: Added databinding for cloneCipher callback
- **Organization: vault.component.ts**:  Added cloneCipher method. Sets the necessary add/edit variables for proper adjustment
- **add-edit.component.html**: Allowed ownership/collection …
=> Implement Clone item functionality (personal/org)

src/app/organizations/manage/policies.component.html, src/app/organizations/manage/policy-edit.component.html, src/app/organizations/manage/policy-edit.component.ts, src/locales/en/messages.json
Updated some UI on other policy screens. Code cleanup.
=> Admin config for master password policy

src/app/organizations/manage/policies.component.ts, src/app/organizations/manage/policy-edit.component.html, src/app/organizations/settings/two-factor-setup.component.ts, src/app/settings/two-factor-setup.component.html, src/app/settings/two-factor-setup.component.ts, src/locales/en/messages.json
Localize descriptions and add warnings for two-step login policies.
=> Add copy descriptions and warnings to policies

src/app/accounts/register.component.ts
We need to evaluate some policies when a user is registering from an org invite. This will load those new policies to use on the registration component. @vincentsalucci can implement these as needed for evaluating the master password.
=> load policies on register if org invite

src/app/accounts/register.component.ts, src/app/settings/change-password.component.ts
- **register.component.ts**: Added break statements to grab the correct score string to display
- **change-password.component.ts**: Added break statements to grab the correct score string to display
=> Fix password score display switch statement

src/app/organizations/manage/people.component.html, src/app/organizations/manage/people.component.ts
I implemented my feature request myself:
https://community.bitwarden.com/t/show-total-number-of-licensed-users-per-organization/10937
Does this make sense for you?
=> Total number of organization users added

src/app/services/services.module.ts, src/locales/en/messages.json
- **jslib**: Update from `28e3fff` to `72e3893`
- **messages.json**: Updated lock description for translators
- **services.module.ts**: Updated `vaultTimeoutService` init
=> Update jslib (28e3fff -> 72e3893)

src/app/services/services.module.ts, src/app/settings/options.component.ts, src/locales/en/messages.json
> Users selecting the `Log Out` timeout action need to be made more aware of the necessary requirements for accessing their vault next time.
- **options.component.ts**: Added warning dialog if selected vault action is `logOut`. 
- **messages.json**: Added title and body for warning dialog
=> [Auto Logout] Added warning dialog for log out action

src/app/accounts/register.component.html, src/app/accounts/register.component.ts
This stubs out the layout pages for marketing team
=> stub alternate layout support for register page

src/app/layouts/organization-layout.component.ts, src/app/services/services.module.ts
> Provide the web portal with a way to handle the enterprise portal environment URL
- **jslib**: Updated from 2b6657a to 28d21ca
- **organization-layout.component.ts**: Added `EnvironmentService` to constructor in order to access the service during init.  Adjusted the `enterpriseUrl` based on the presence of either a saved enterprise url or a saved base url.
- **services.module.ts**: Added dev conditional for url setting
=> [Enterprise] Added environment checks

src/app/layouts/organization-layout.component.html, src/app/layouts/organization-layout.component.ts, src/app/organizations/manage/group-add-edit.component.html, src/app/organizations/manage/user-add-edit.component.html
- Made user and group add/edit modals the large size to better accommodate the table switch increase
- Added "learn more" icons to help articles about user types and user access
- Update jslib
=> a few tweaks for hidden passwords

src/app/accounts/register.component.ts, src/app/layouts/organization-layout.component.ts
Capture and pass referenceId to the server on registration.
* **Register Component** - set referenceId from passed in query string OR cookie
=> Added referenceId to register component

package-lock.json, src/app/layouts/organization-layout.component.html, src/app/layouts/organization-layout.component.ts, src/app/services/services.module.ts
> Create a way to segue into the enterprise/business portal
- **organization-layout.component.html**: Added `Enterprise` button
- **organization-layout.component.ts**: Added method to launch enterprise portal based on the supplied URL.
=> [Enterprise] Added button to launch portal

src/app/services/services.module.ts
> Update all Kestrel application urls to use the current IIS configuration
[Local Dev: Port Sync](https://github.com/bitwarden/company/wiki/Local-Dev:-Port-Sync)
- **services.module.ts**: Updated enterprise dev url to use newly assigned port
=> [Settings] Port Sync

package-lock.json, src/app/accounts/lock.component.html, src/app/accounts/lock.component.ts, src/app/accounts/login.component.html, src/app/accounts/sso.component.html, src/app/accounts/sso.component.ts, src/app/app-routing.module.ts, src/app/app.component.ts, src/app/app.module.ts, src/app/layouts/organization-layout.component.html, src/app/layouts/organization-layout.component.ts, src/app/services/services.module.ts, src/connectors/sso.html, src/connectors/sso.scss, src/connectors/sso.ts, src/services/htmlStorage.service.ts, src/services/webPlatformUtils.service.ts, webpack.config.js
- sso component to kick off sso auth flow
- sso connector to catch redirect callback from sso flows
=> SSO support

src/app/accounts/register.component.ts
Ensure we pass layout, flow and reference id in the new reference data parameter when registering a new user. Will break until jslib is updated.
=> Transition reference id to data

src/app/services/services.module.ts, src/services/webPlatformUtils.service.ts
Changes to ensure compatibility with bitwarden/jslib#119
=> Support biometric changes in jslib

src/app/accounts/sso.component.ts
Client id must be specific to each client using this component.
=> Support for dynamic clientid

src/app/organizations/settings/account.component.html, src/app/organizations/settings/account.component.ts, src/locales/en/messages.json
- Update jslib
- Allow updating org identifier from settings pages
=> implement identifier update in org settings

package-lock.json, package.json
Forgot to upgrade this dependency when upgrading to Angular 9.
=> Upgrade Angular CDK

src/app/accounts/change-password.component.html, src/app/accounts/change-password.component.ts, src/app/app-routing.module.ts, src/app/settings/change-password.component.html, src/app/settings/change-password.component.ts, src/locales/en/messages.json
The existing set password flow did not work due to missing keys and other crypto related proeprties on the user account which are not set yet. This upadte extends the change password component to support the set password flow for new sso users.
=> call api to set password with key parameters

src/app/accounts/login.component.html, src/app/accounts/sso.component.html, src/app/accounts/sso.component.ts, src/app/app-routing.module.ts, src/app/layouts/organization-layout.component.html, src/connectors/sso.html, src/locales/en/messages.json, src/services/htmlStorage.service.ts
- Update jslib
- Localize various SSO-related strings
- Save and pre-populate last-used org identifier
- Allow org identifier to be passed in via query string
=> cleanup various sso tasks

src/app/settings/organization-plans.component.html, src/app/settings/organization-plans.component.ts
Some small cleanup items and bug fixes for the recent plan changes.
=> few fixes to plan changes

src/app/settings/organization-plans.component.html, src/locales/en/messages.json
Per requests from marketing this PR makes some changes to the structure and wording of products on the organization create page.
- Capitalized some feature keywords, like Groups, Collections, etc.
- Added blurbs for SSO and Enterprise Policies
- Changed the Enterprise feature list from a 1-1 list into a "Includes everything from Teams +" style messge.
Requested changes were sourced from [here](https://docs.google.com/document/d/1iA3Yqr2Hpl13EaHsFxwRhjk-avh77qNdEmcdB-lY4Tc/edit?ts=5f3c3b6c).
=> Product description updates

src/app/accounts/set-password.component.html, src/app/accounts/set-password.component.ts, src/app/accounts/two-factor.component.ts
> For potentially long-lasting sync operations on the initialization of the `set-password` flow. Add a loading placeholder.
- **jslib**: Update from e55528e to 700e945
- **set-password.component.html**: Add sync loading placeholder
- **set-password.component.ts**: Add `syncService` dependency
- **two-factor.component.ts**: Remove unnecessary references to `resetMasterPassword` variable that is now deleted (fixes build)
=> [SSO] Add set-password loading placeholder

src/app/organizations/settings/account.component.html, src/app/organizations/settings/account.component.ts
These fields cannot be modified when self-hosted
=> disable certain org settings fields when selfhost

src/locales/en/messages.json
New localization string keys for SSO pre-validation messages. (_and fixed a very small formatting issue_).
=> SSO pre-validation messages

src/app/settings/organization-plans.component.ts
Filter out custom plans from the organization create screen
=> Add Custom Plan Static Store Item

src/app/accounts/sso.component.html
Fixed pre-validation messaging in the web vault for SSO.
=> form promise added for sso prevalidation

src/app/settings/link-sso.component.html, src/app/settings/organizations.component.html, src/locales/en/messages.json
Added localization variables for Link and Unlink SSO
=> added localization variable for link sso

src/app/organizations/manage/collection-add-edit.component.html, src/app/organizations/manage/user-add-edit.component.html, src/app/vault/add-edit.component.html, src/app/vault/folder-add-edit.component.html
resolves and closes #324 
added to modals:
- invite user
- add item
- add collection
- add folder
=> ♿️ added autofocus on first field of modal forms - closes #324

src/app/organizations/manage/policies.component.html, src/app/organizations/manage/policies.component.ts, src/app/organizations/manage/policy-edit.component.html, src/app/settings/organization-plans.component.html, src/app/settings/organization-plans.component.ts, src/locales/en/messages.json, src/scss/styles.scss
As an enterprise organization admin I want to be able to block members of my organization from being able to be a part of other organizations.
1. A policy (OnlyOrg) exists that restricts non-admin members from being able to be a part of other organizations.
2. When applying the OnlyOrg policy any non-owner members who aren't the one enabling the policy & that are already in another org should be removed from the org applying the policy. This user flow should mirror what already exists for the 2FA policy.
3. Admins should be warned about users potentially being removed before enabling the Only Org policy
4. Removed users should get an email informing them of the removal.
5. The OnlyOrg policy needs to be configurable from the web vault AND the enterprise portal.
6. A message is displayed …
=> OnlyOrg Policy

src/app/organizations/manage/policies.component.ts, src/app/organizations/manage/policy-edit.component.html, src/app/organizations/manage/policy-edit.component.ts, src/app/settings/organization-plans.component.html, src/app/settings/organization-plans.component.ts, src/locales/en/messages.json
It has been requested that we change the verbiage of the new OnlyOrg policy to be SingleOrg instead, this per fulfills that.
[Asana Ticket](https://app.asana.com/0/1195018406457675/1198564632123101)
https://github.com/bitwarden/server/pull/974
=> Only org to single org

src/app/accounts/register.component.html, src/app/accounts/register.component.ts, src/locales/en/messages.json
> In order to complete GDPR compliance, moving forward with new user creation, we need to have explicit user interaction for Terms of Service and Privacy Policy acknowledgement.
- **register.component.html**: Removed old acceptance views. Added new checkbox and label elements. Styled similarly to other helper text within this component. 
- **messages.json**: Added label message and error message for policy acceptance.
- **jslib**: Update jslib from 76c0964 to 5e50aa1
=> [GDPR] Adjusted TOS/Privacy acceptance

src/app/send/add-edit.component.html, src/app/send/send.component.html, src/app/send/send.component.ts, src/locales/en/messages.json
Bring over some basic filtering logic from the vault listing to the Send listing. Not fully functional yet, but it works somewhat.
=> some filtering logic for sends

CONTRIBUTING.md
This expands the contributing guide to bring it into line with the changes made here: https://github.com/bitwarden/browser/pull/1421
=> Docs contrib

src/app/send/add-edit.component.ts, src/app/send/send.component.ts, src/app/services/services.module.ts
Implement jslib's new send service through send components.
=> send service implementation

src/services/webPlatformUtils.service.ts
=> Change supportsSecureStorage to false

src/app/organizations/tools/export.component.ts, src/app/settings/change-password.component.ts, src/app/tools/export.component.html, src/app/tools/export.component.ts, src/locales/en/messages.json
- Added needed components to support .json encrypted format from the web vault.
- Added warning messages about rotating the encryption key with encryption exports.
=> encrypted json export option for user and orgs

src/app/tools/import.component.ts
Passes in the org id to the import service.
=> update getImporter signature pass org id

src/app/tools/import.component.html
Adds mac importer to 1Password import help instructions
=> Add help text for jslib's mac importer

src/app/vault/groupings.component.html
Adaptation of https://github.com/bitwarden/desktop/pull/303 for the web vault.
=> Only show carats for items with children

src/app/vault/add-edit.component.html
This fixes Password History Overflow #738
=> Password History Overflow

package-lock.json, src/services/webPlatformUtils.service.ts
Resolved the API abstraction change from https://github.com/bitwarden/jslib/pull/161 for web.
=> update jslib and fix webPlatformUtils

src/app/services/event.service.ts, src/locales/en/messages.json
Related to bitwarden/web/issues/686. Fill out description for sso user unlink even for the event log.
* **messages.json**: messaging for user unlinking sso from organization
* **event.service.ts**: Handle sso unlink event
Waiting on bitwarden/jslib#231
=> Add message for missing event type

.github/workflows/build.yml
Fixing incorrectly named secret in workflow
- .github/workflows/build.yml
=> fixing incorrect secret name

src/app/tools/export.component.html, src/locales/en/messages.json
React to PR https://github.com/bitwarden/jslib/pull/238
=> warning dialog is now handled in base component

src/app/send/access.component.html, src/app/send/access.component.ts, src/app/send/add-edit.component.html, src/app/send/send.component.html, src/app/send/send.component.ts, src/app/vault/add-edit.component.html, src/locales/en/messages.json
- Move remove password and delete functions to send service, which properly handles updating server and local data
- Status icons on send listing page
- New string for disabled checkbox
- Max access count cannot be set to less than 1
- Better error messages for 404 and other errors when accessing send
- Remove auto-text selection on text send access
=> send improvements and bug fixes

src/app/settings/two-factor-recovery.component.ts
As I described in the issue #759, the `Print Code` button did not work correctly.
My PR will make sure the window will open up then close after the Code is printed completely.
Happy New Year 🎉🎉🎉
=> Fix #759 for Print Code button in Two-step Login

src/app/settings/organization-plans.component.html
Fix #782.
Fix reference to component property
=> Fix missing subscription frequency

src/app/app-routing.module.ts, src/app/layouts/navbar.component.html, src/app/send/send.component.ts
*This PR will be marked as ready when jslib updates are merged & added*
https://app.asana.com/0/1199659118818122/1199511462356833
https://github.com/bitwarden/server/pull/1106
https://github.com/bitwarden/jslib/pull/250
As a Bitwarden Send user I would like my local Send storage to stay in sync across concurrent sessions.
1. Enabled Send by removing the comment out route & header link.
2. Added a subscription event to the Send component to check for any new Sends.
=> Send Sync Notifications

src/app/send/add-edit.component.ts, src/app/send/send.component.ts
> Implement the newly ported send components
- **jslib**: Updated from 9ddec9b to 859f317
- **send/add-edit.component.ts**: Extended base class. Removed duplicated code.
- **send/send.component.ts**: Extended base class. Removed duplicated code. First iteration seems to yield an empty class - will continue to update this as necessary.
=> [Send] Port web base components

src/app/settings/emergency-access-takeover.component.html, src/app/settings/emergency-access-takeover.component.ts, src/app/settings/emergency-access.component.html, src/app/settings/emergency-access.component.ts, src/locales/en/messages.json
This PR is required to support the changes described in https://github.com/bitwarden/server/pull/1132. Refer to that PR for explanation.
=> Improved handling of grantor access to organizations after takeover

src/app/send/send.component.ts
> Update `jslib` to latest and correct any flow changes
-**send.component**: Added constant for subscriberID. Updated constructor. Added Broadcaster actions to `onInit/onDestroy`. **NOTE:** none of this is new functionality, just moved from the base class.
Needs latest `jslib` changes found [here](https://github.com/bitwarden/jslib/pull/270)
=> [Send] Update jslib and Send component

src/app/settings/premium.component.html, src/locales/en/messages.json
Added "Emergency Access" to  src/app/settings/premium.component.html and messages.json
=> Add Emergency Access to Get Premium

src/app/send/access.component.html, src/app/send/access.component.ts, src/locales/en/messages.json
jslib will need to be updated to https://github.com/bitwarden/jslib/pull/284 for this to build.
Added some flair to the BW Send access page after marketing feedback.
1. The "A bitwarden user..." message
2. Expiration date under file/text
3. Blurb about what BW Send is w/ links to help article and account registration
=> updated send access component

src/app/settings/change-kdf.component.html
Replaced the Learn More link of [PBKDF-2](https://en.wikipedia.org/wiki/PBKDF2) with https://bitwarden.com/help/article/what-encryption-is-used/#pbkdf2
=> Replace learn more link

src/app/send/access.component.ts, src/locales/en/messages.json
Implements download link request scheme from bitwarden/jslib#288 and bitwarden/server#1174.
* **access.component.ts**: request download link.
* **messages.json**: report if file cannot be found due to missing download link.
Depends on bitwarden/jslib#288
=> Use download link requests

src/app/settings/organization-plans.component.ts
Required to support the changes here: https://github.com/bitwarden/server/pull/1171
Specifically, single organization policy (SOP) is checked client-side when creating a new org.
=> Exclude owners and admins from single organization policy when creating new org

.github/workflows/build.yml
Adding in some automation to support a release specific branch for stable testing.
- .github/workflows/build.yml
=> Add rc auto

.github/workflows/build.yml
Adding the docker account to the `rc` branch workflow.
- .github/workflows/build.yml
=> adding docker to the rc branch workflow

src/app/services/services.module.ts
Depends on bitwarden/jslib#296.
Provides DI and current constructor to SendService
=> Azure upload blobs

src/app/layouts/footer.component.ts, src/app/layouts/frontend-layout.component.ts, src/app/services/services.module.ts, src/services/webPlatformUtils.service.ts
I added some breaking changes to jslib https://github.com/bitwarden/jslib/pull/332, bumping jslib to resolve this issues for everyone else.
=> [Chore] Bump jslib

src/app/settings/organizations.component.html, src/app/settings/organizations.component.ts
> Disable `Reset Password` functionality with feature flag until general release.
- **organizations.component.html**: Added conditional with feature flag's status. Currently will block initial enrollment option.
- **organizations.component.ts**: Added extra layer of security to return from enrollment method.
=> [Reset Password] Feature Flag

package-lock.json, package.json
> Bump version from 2.19.0 -> 2.20.0
- **package.json**: Minor version bump to 2.20.0
- **package-lock.json**: Minor version bump to 2.20.0
=> [Version] Bumped to 2.20.0

src/app/organizations/vault/ciphers.component.ts
Pull in fix from bitwarden/jslib#356.
=> Specify organization id as the indexing entity

src/app/organizations/vault/vault.component.html, src/app/organizations/vault/vault.component.ts, src/app/vault/vault.component.html, src/app/vault/vault.component.ts, src/locales/en/messages.json
Now that trashed items will be automatically deleted after a while we should notify users. Since we don't know the frequency for self-hosted instances there are two different phrasings one specifying 30 days and one generic.
=> Add auto delete warning to trash page

.github/workflows/build.yml
Rotate the delegate key for docker image signing
=> Updating the docker signing key

.github/workflows/build.yml
Adding in the missing repo passphrases for the docker push tasks
=> fixing docker push

.github/workflows/build.yml
Update docker tag command with proper arguments.
=> Fix docker tag version in workflow

src/app/services/services.module.ts, src/locales/en/messages.json
Required to support https://github.com/bitwarden/jslib/pull/369.
=> Check encKey when importing encrypted JSON

src/app/organizations/vault/ciphers.component.ts
Fix organization web vault advanced search for non-privileged users.
Fix is to set ciphers and index for all users.
This will be pulled in as a hotfix to `rc`
=> Set search index for limited collection org users

src/locales/en/messages.json
Rename Ciphers -> Items in trash cleanup message.
=> Rename Ciphers -> Items in trash cleanup message

package.json
=> Version bump for org search hot fix

package-lock.json, package.json
=> Bump version to 2.20.3

package.json
=> bumping version 2.20.4

.github/workflows/release.yml
Wasn't grabbing the Release version correctly in the release workflow.
=> fixing the release workflow

src/app/settings/change-password.component.html
=> Fix non-unique ids

entrypoint.sh
Copy `assetlinks.json` to `app` dir
=> Copy assetlinks.json to app dir

.github/workflows/build.yml
Adding in a new build job to create the capability of building/publishing the QA environment docker image alongside the selfhost image.
=> Add qa container

src/services/htmlStorage.service.ts, src/services/memoryStorage.service.ts
The recent jslib bump changed the `storageService` interface, to add a `has` method: https://github.com/bitwarden/jslib/pull/402
This PR updates the browser's implementations of this interface.
=> Update storageService implementations

src/app/vault/add-edit.component.html
Add help link to password reprompt option.
´
=> Add reprompt help link

src/connectors/captcha.html, src/connectors/captcha.scss, src/connectors/captcha.ts, webpack.config.js
Adds support for captcha connector that can be consumed via iframe from other Bitwarden clients for solving HCaptcha challenges.
=> add captcha connector

src/app/settings/organization-plans.component.html, src/app/settings/organization-plans.component.ts
The `OrganizationPlansComponent` is difficult to follow and has three different flows depending on the criteria. I've refactored `submit()` it into a few smaller functions which better describe what happens, and cleaned up the conditional flow to avoid multiple if statements.
This is a preparatory step towards being able to add yet another flow for providers.
=> Refactor OrganizationPlansComponent

package-lock.json, package.json
> Bump version for upcoming release from `2.20.4` -> `2.21.0`
- **package-lock.json**: Bumped version
- **package.json**: Bumped version
=> [Version] Bumped to 2.21.0

package-lock.json, package.json
Solves an issue where the braintree dropin gets stuck in an infinite spinner if `paymentOptionPriority` is set. https://github.com/braintree/braintree-web-drop-in/blob/main/CHANGELOG.md
Note: This PR will be cherry picked to `rc` branch.
=> Bump braintree to 1.30.1

src/app/organizations/manage/bulk/bulk-confirm.component.ts
See https://app.asana.com/0/1169444489336079/1200570295565473/f
Notes:
* build is failing due to jslib changes
* I expect this will be cherry-picked into `rc`
Requires PRs:
* jslib: https://github.com/bitwarden/jslib/pull/425
* server: https://github.com/bitwarden/server/pull/1442
=> Fix fingerprint phrases

src/app/oss.module.ts, src/services/i18n.service.ts
Added AZ language and adjusted locale import to be alphabetical again.
=> add AZ language

src/app/organizations/manage/bulk/bulk-confirm.component.html, src/app/organizations/manage/bulk/bulk-remove.component.html, src/app/organizations/manage/bulk/bulk-status.component.html, src/app/organizations/manage/entity-events.component.ts, src/app/organizations/manage/entity-users.component.html, src/app/organizations/manage/events.component.ts, src/app/organizations/manage/people.component.html, src/app/organizations/manage/people.component.ts, src/app/oss.module.ts, src/app/settings/emergency-access.component.html, src/app/settings/emergency-access.component.ts, src/app/settings/profile.component.html
In #1014 we noticed there are some inconsistencies in how user names are displayed, sometimes the name is trimmed and sometimes it's not. The new `UserNamePipe` ensures that names will be consistently displayed throughout the app.
Depends on https://github.com/bitwarden/jslib/pull/429
=> Use UserNamePipe

crowdin.yml
@dltmurphy @cscharf - mapping for the Serbian language to default to Cyrillic.
=> Added mapping for Serbian Cyrillic

bitwarden_license/src/app/providers/providers-routing.module.ts, src/app/layouts/navbar.component.html, src/app/layouts/navbar.component.ts, src/app/providers/providers.component.html, src/app/providers/providers.component.ts, src/app/vault/vault.component.html
Adds a link to the users provider. The link is only visible if the user belongs to a provider, and if the user only belongs to a single provider, it will link directly to that provider.
- **bitwarden_license/src/app/providers/providers-routing.module.ts**: Add url for viewing providers.
- **src/app/layouts/navbar.component.{ts, html}**: Add link to navbar.
- **src/app/providers/providers.component.{ts, html}**: Add support for a more full-screen provider view.
https://app.asana.com/0/1198901840263430/1200623666598577
=> [Provider] Add provider link in navbar

bitwarden_license/src/app/providers/settings/account.component.html, bitwarden_license/src/app/providers/setup/setup.component.html, bitwarden_license/src/app/providers/setup/setup.component.ts, src/app/settings/organization-plans.component.html, src/app/settings/organization-plans.component.ts, src/locales/en/messages.json
Fix for https://app.asana.com/0/1153292148278596/1200645727236059/f
Includes messages changes and removing `business name` from provider views.
=> Fix setup provider page

src/locales/en/messages.json
Fixes: https://app.asana.com/0/0/1200645727236055/f
tweak to Provider Admin description
=> Clarify admin provider description

bitwarden_license/src/app/providers/clients/add-organization.component.ts, src/app/settings/organization-plans.component.html
Fixes: https://app.asana.com/0/1153292148278596/1200652187192755/f
Providers can only create business-level organizations. Alter org-plans form accordingly.
Depends on #1101
=> Show only business org create form if provider

src/assetlinks.json, webpack.config.js
Possible fix for inability to access via Google's fido lib
=> Add assetlinks.json to webpack.config.js

src/app-id.json
Add debug key hash for testing fido lib
=> Add debug key hash

bitwarden_license/src/app/providers/clients/clients.component.html, bitwarden_license/src/app/providers/clients/clients.component.ts, bitwarden_license/src/app/providers/setup/setup.component.ts, src/locales/en/messages.json
Fixes
* https://app.asana.com/0/0/1200645727236021/f
* title case strings in messages
* https://app.asana.com/0/0/1200645727236027/f
* remove org create from clients page if not provider admin
* https://app.asana.com/0/0/1200645727236033/f
* title case messages
* https://app.asana.com/0/0/1200687814632015/f
* Do not display toast popup as title (null title)
Various product feedback fixes.
=> Batch web provider fixes

src/assetlinks.json, webpack.config.js
Reverts bitwarden/web#1114 - was not the cause of the regression issue
=> Revert "Revert "Add assetlinks.json to webpack.config.js""

package-lock.json, package.json
=> Version bump to 2.22.0

package-lock.json, package.json
=> Bump version to 2.22.1

src/locales/zh_CN/messages.json, src/locales/zh_TW/messages.json
In the last Crowdin sync, the Chinese languages got swapped. This reverts those changes
=> Reverting the Chinese translations that got swapped

package-lock.json, package.json
=> Bump version to 2.22.3

.github/workflows/build.yml, .github/workflows/crowdin-sync.yml, .github/workflows/deploy.yml, .github/workflows/qa-deploy.yml, .github/workflows/release.yml
These changes were based off the linter output.
=> Update workflows with linter suggestions

src/app/services/event.service.ts, src/locales/en/messages.json
Add event logging for https://github.com/bitwarden/server/pull/1560.
Depends on jslib PR: https://github.com/bitwarden/jslib/pull/475.
=> Add event logging for ResetSsoLink

.github/ISSUE_TEMPLATE/bug.yml
Updates the issue template with additional context, and simplifies the labels for OS and browser versions.
=> Add additional context to issue template

.github/workflows/build.yml
Adding a file to the QA image via the CI pipeline to enable easy tracking the version of the currently deployed web client to the QA environment. We are also changing the displayed version a bit as well by adding the small GitHub SHA
=> Adding QA info.json file

src/app/accounts/set-password.component.html
> Fix typo in `set-password` html binding
- **set-password.component.html**: Removed an extra "s" in password - fixed binding to variable
- Will be merged into `master` and `rc`
=> [SSO/Auto Enroll] Fixed typo for banner

src/app/oss.module.ts, src/app/vault/add-edit-custom-fields.component.html, src/app/vault/add-edit-custom-fields.component.ts, src/app/vault/add-edit.component.html
Web implementation of https://github.com/bitwarden/jslib/pull/489.
=> Move custom fields to separate components

.github/workflows/deploy.yml
Adding temp deploy workflow on `master` to enable the deploy workflow on `rc`
=> Adding temp workflow

.github/workflows/build.yml, .github/workflows/qa-deploy.yml, .github/workflows/release.yml
Ran the new linter over the web project and found some errors that need fixing.
=> Hotfix some errors found via linter

.github/workflows/build.yml, .github/workflows/crowdin-pull.yml
Update the Crowdin Sync process by adding a push of the sources on every build of `master`.  Add a scheduled trigger to the Crowdin pull to pull every Friday at midnight, to align with the dev complete 
* **.github/workflows/build.yml:** Adding Crowdin pushes on `master` builds
* **.github/workflows/crowdin-pull.yml:** Scheduling the Crowdin pull on Friday at midnight.
This is a test-in-production scenario where we have to merge into `master` and see if it works like my interpretation of the documentation.
=> Rework Crowdin Integration

.github/workflows/build.yml, crowdin.yml
Fix the incorrect upload path in Crowdin push
* **crowdin.yml:** preserving file hierarchy and setting the destination path
=> Hotfix Crowdin push

src/connectors/captcha.ts
Ensure that passed parameters to captcha connector are properly sanitized.
Use `encodeURIComponent` to sanitize URL-built parameters.  Also switch mobile callback URI to be a fixed value (`bitwarden://captcha-callback`).
Regression around captcha login scenarios on all clients, particularly mobile.
=> sanitize data inputs for captcha connector

package-lock.json, package.json
Version bump to `v2.24.4`.
* **package.json:** Version bump to `v2.24.4`.
* **package-lock.json:** Version bump to `v2.24.4`.
=> Version bump to v2.24.4

src/connectors/duo.ts, src/connectors/sso.ts, src/connectors/webauthn.ts
Fix linting errors caused by recent changes to connectors. CC @kspearrin 
* use const instead of let/var
* delete whitespace
None required, these are pure style fixes that should not have any impact. You could do basic regression testing on duo, SSO and webauthn if you wanted, but I don't think it's required.
=> Fix linting in connectors

src/app/services/services.module.ts
In #1256 we added the `KeyConnector` as a depdendency to `VaultTimeoutService`, unfortunately this dependency got set to null in `web`. 
Resolves https://app.asana.com/0/1198901840263430/1201354859765795
=> Add required KeyConnectorService to vaultTimeoutService

src/app/settings/settings.component.ts, src/app/vault/vault.component.html, src/app/vault/vault.component.ts, src/locales/en/messages.json
Use a helper function to show redeem items at the right time
=> Families for enterprise/redeem card

src/app/oss.module.ts, src/app/settings/sponsored-families.component.html, src/app/settings/sponsored-families.component.ts, src/app/settings/sponsoring-org-row.component.html, src/app/settings/sponsoring-org-row.component.ts, src/locales/en/messages.json
Create a component for table rows so both buttons show as loading at the correct times.
=> Split table rows into component so buttons load

src/app/organizations/settings/organization-subscription.component.ts, src/app/settings/sponsored-families.component.ts, src/app/settings/sponsoring-org-row.component.ts, src/locales/en/messages.json
=> Families for enterprise/localizations

src/app/organizations/settings/delete-organization.component.ts, src/app/services/services.module.ts, src/app/settings/api-key.component.ts, src/app/settings/deauthorize-sessions.component.ts, src/app/settings/delete-account.component.ts, src/app/settings/purge-vault.component.ts, src/app/settings/two-factor-verify.component.ts
Follow up to https://github.com/bitwarden/jslib/pull/544, where we decided to throw errors from `UserVerificationService` and catch them in the components if required.
* **src/app/services/services.module.ts** - update service dependencies. Change `useClass` to `useValue` for `userVerificationService`, because we removed the `@Injectable` decorator from the base component.
* all other files: move the call to `userVerificationService` into the nearby try/catch block, and display any error that occurs to the user.
https://github.com/bitwarden/jslib/pull/544 must be merged first.
Regression testing on verify password/OTP components.
=> Update jslib and use new UserVerificationService pattern

bitwarden_license/src/app/organizations/manage/sso.component.html, bitwarden_license/src/app/organizations/manage/sso.component.ts, src/app/organizations/policies/master-password.component.ts, src/app/organizations/policies/reset-password.component.ts, src/locales/en/messages.json
Disabled the key connector option in SSO when org doesn't have the feature.
Resolves https://app.asana.com/0/1201363553288890/1201363553288934
Depends on https://github.com/bitwarden/jslib/pull/551
=> Disable key connector when org doesn't have the feature

src/app/services/services.module.ts, src/app/tools/export.component.html, src/locales/en/messages.json
Adds the required language changes for the updated verify master password component.
Depends on: https://github.com/bitwarden/jslib/pull/553
=> Update verify password/otp component

src/app/services/event.service.ts, src/locales/en/messages.json
Depends on https://github.com/bitwarden/jslib/pull/555.
=> [Key Connector] Add firstSsoLogin event

src/app/common/base.people.component.ts, src/app/organizations/manage/people.component.ts, src/locales/en/messages.json
Adds a new warning when removing an organization user using key connector.
Depends on https://github.com/bitwarden/jslib/pull/559
Resolves https://app.asana.com/0/1201363553288890/1201385116854988
=> Update warning when removing an account using key connector

src/app/organizations/manage/people.component.ts, src/app/organizations/manage/user-add-edit.component.ts
In #1307 I updated the warning when removing an account from an organization that is using key connector. QA noticed that the warning wasn't updated when deleting from the view modal.
=> [KeyConnector] Updated remove warning in details view

bitwarden_license/src/app/organizations/manage/sso.component.html, bitwarden_license/src/app/organizations/manage/sso.component.ts
Fix bug from https://github.com/bitwarden/web/pull/1291: we were testing the Key Connector URL even if the Key Connector was not enabled. Also some of the logic in `submit()` was wrong.
* **bitwarden_license/src/app/organizations/manage/sso.component.ts**:
* only test Key Connector URL if it's enabled
* fix logic so that we don't test the URL again if it's already been tested and hasn't changed since then.
=> [Key Connector] Fix Key Connector Url test

src/app/organizations/settings/account.component.ts, src/app/organizations/settings/delete-organization.component.ts, src/app/organizations/sponsorships/families-for-enterprise-setup.component.ts, src/app/settings/organization-plans.component.html, src/app/settings/organization-plans.component.ts, src/app/settings/sponsoring-org-row.component.ts, src/locales/en/messages.json
Refactored the organization plan component so that it would reflect the actual price of the organization. Since they are getting a sponsored families plan the basePrice is dropped off and now all calculations on the screen are correct for what they will be responsible for paying.
I also ran linting that I hadn't ran it after I made PR changes.
Validate that the proper price is displayed throughout the screen.
=> Fix basePrice to reflect the sponsorship

src/app/settings/sponsored-families.component.html, src/app/settings/sponsoring-org-row.component.html, src/app/settings/sponsoring-org-row.component.ts, src/locales/en/messages.json
Asana Task:  https://app.asana.com/0/1169444489336079/1201440862306277/f
* Display sponsorship warning when sponsoring an org
* Move actions to drop down menu
* Fix revoke cancel success popup
Test layout matches Figma. Test cancelling revoke request.
=> Fix families sponsorship redeem page

src/app/accounts/lock.component.ts, src/app/accounts/login.component.ts, src/app/app.component.ts, src/app/services/services.module.ts, src/app/vault/vault.component.ts, src/services/broadcasterMessaging.service.ts, src/services/htmlStorage.service.ts
We currently initialize all our services manually in `ServicesModule`. This makes it a bit cumbersome since we have to define everything in order, and should make it easier to detect bad patterns like circular dependencies.
~~This should also open up for us to define the core dependencies in `jslib` and only define what we need to override in each application.~~ I've moved most of the DI initialization to jslib, https://github.com/bitwarden/jslib/pull/565.
We should be a bit vigilant during regression testing and verify everything works.
=> BEEEP: Refactor services DI

src/404.html
As the year 2022 has arrived it's time to update our copyright in various places.
Asana task: https://app.asana.com/0/1200804338582616/1201609982295258/f
- **src/404.html:** Update year in copyright to 2022
Nothing really to test here other than to verify we show the current year in the copyright.
=> Update year in copyright

package.json
The pre-commit hook which was added recently, did not run on all files (missed html for example).
- **package.json:** Add all files to prettier with lint-staged and ignore via .prettierignore
=> Add all filetypes to prettier and ignore via .prettierignore

package.json
Add --ignore-unknown to prettier
- **package.json:** add the `--ignore-unknown` to lint-staged
=> Add --ignore-unknown to prettier on lint-staged

src/app/accounts/two-factor.component.html, src/connectors/webauthn-mobile.html, src/connectors/webauthn.html
I apparently didn't run prettier correctly for #1232
=> Run prettier on #1232

tsconfig.json
Use the shared `tsconfig` from jslib as base.
=> [BEEEP] Use shared tsconfig

src/locales/en/messages.json
Through the PR https://github.com/bitwarden/web/pull/1385 the update of the fingerprint phrase text was requested. Received an updated copy from product.
Asana task: https://app.asana.com/0/1200885895476554/1201645511129672/f
- **src/locales/en/messages.json:** Updated text of `dontAskFingerprintAgain`
=> Update copy on fingerprint phrase prompt

src/app/services/services.module.ts
Update jslib to pull in changes to state data structure, and migration of settings for logged out accounts to the new typed data structure. 
* Added the AccountFactory parameter needed to construct client-specific account objects to services.module
=> [chore] Update jslib

src/app/vault/vault.component.html, src/app/vault/vault.component.ts
We've decided to remove the card for families for enterprise on the vault screen.
https://app.asana.com/0/0/1201627072707277/f
- **src/app/vault/vault.component.html:** Removed card
- **src/app/vault/vault.component.ts:** Removed logic of when to show card
=> Remove F4E vault card

src/app/settings/options.component.ts, src/theme.js
https://app.asana.com/0/1201648796371593/1201735745560300
Setting theme is not working.
On https://github.com/bitwarden/jslib/pull/611 we updated the storage model to have globals as a top level item, removing the all knowing "state" field. These changes were never implemented in theme.js in web, which is causing it to not find a theme.
* Update theme.js to pull theme from the right location
=> [bug] Update theme.js to refelect new storage structure

bitwarden_license/src/app/organizations/manage/sso.component.html, bitwarden_license/src/app/providers/manage/user-add-edit.component.html, src/app/accounts/recover-two-factor.component.html, src/app/app.component.ts, src/app/organizations/manage/bulk/bulk-confirm.component.html, src/app/organizations/manage/group-add-edit.component.html, src/app/organizations/manage/user-add-edit.component.html, src/app/organizations/manage/user-confirm.component.html, src/app/organizations/settings/download-license.component.html, src/app/send/access.component.html, src/app/settings/change-kdf.component.html, src/app/settings/change-password.component.html, src/app/settings/change-password.component.ts, src/app/settings/emergency-access-add-edit.component.html, src/app/settings/emergency-access-confirm.component.html, src/app/settings/emergency-access.component.html, src/app/settings/options.component.html, src/app/settings/profile.component.html, src/app/settings/update-key.component.html, src/app/tools/import.component.html, src/app/vault/add-edit-custom-fields.component.html, src/app/vault/add-edit.component.html, src/app/vault/attachments.component.html, src/app/vault/groupings.component.html, src/app/vault/vault.component.html
remove /article/  and help.bitwarden.com references
Update links to correct location
link updates
Test links for accuracy
=> Update help site URLs

src/app/organizations/manage/bulk/bulk-confirm.component.html, src/app/organizations/manage/user-confirm.component.html, src/app/settings/emergency-access-confirm.component.html, src/app/tools/import.component.html
=> Apply prettier on help pr

src/scss/styles.scss, webpack.config.js
Adds CSP rules to the webpack dev server. This will ensure that we don't accidentally modify anything that requires updates to CSPs.
While at it, I also updated sweetalert2 to not insert inline styling.
Asana: https://app.asana.com/0/1201332233342092/1201340159635907
Regression testing to ensure sweetalert still behaves as expected.
=> Add CSP for development

package-lock.json, package.json, src/app/organizations/vault/vault.component.html, src/app/send/send.component.html, src/app/vault/add-edit.component.html, src/app/vault/bulk-actions.component.html, src/app/vault/ciphers.component.html, src/app/vault/groupings.component.html, src/app/vault/vault.component.html, webpack.config.js
> Remove all instances of `FA` and make any requested icon changes. Merge to both `master` and `rc` once approved.
- **package.json**: Removed `FA` node module from the web application
- **package-lock.json**: Updated due to `package.json` changes
- **vault.component.html**: Changed padding to match desired button layout
- **send.component.html**: Changed padding to match desired button layout
- **add-edit.component.html**: Icon updates - `refresh` -> `generate` - `share` -> `share-square`
- **bulk-actions.component.html**: Icon update - `share` -> `folder`
- **ciphers.component.html**: Changed padding to match desired button layout
- **groupings.component.html**: Icon update - `star-f` -> `star` - `caret-*` -> `angle-*`
- **vault.component.html**: Changed padding to match desired button …
=> [Icons] FF - requested icon changes

bitwarden_license/src/app/organizations/manage/sso.component.html
Selecting a dropdown item different from the default would switch the value of the bound properties to be strings. This would then send it as a string to server and during bitwarden/server#1753 when we switched from Newtonsoft -> STJ for model binding we lost the ability to serialize a string representation of a number into an enum. 
Asana Task: https://app.asana.com/0/0/1201772450952821/f
This will be 🍒⛏️ 
I changed all the remaining dropdowns that are bound to enums that are backed by numbers to have `[ngValue]` instead of just `value` this way angular will bind the numerical value to the request instead of the string representation. I think this is the right move even though the regression occurred on server because most enums in the project are sent as numbers and other properties in …
=> Switch option values to be a number

src/app/accounts/login.component.html
Fix missing icon for the register button on the vault homepage.
Note: This will be 🍒 ⛏️ to rc.
Before:
After:
=> Fix register button using wrong icon

src/app/tools/import.component.ts
Updates jslib and handles changes to import and export. This work only updates requirements without implementing any way for the UI to interact with the new feature.
* **import component**: handle `readonly` on import options and move sort to the import options setup function
* ****:
Just observe the password protect  format options don't exist in import or export
=> Handle password protected import export

src/app/organizations/manage/policy-edit.component.ts
When attempting to enable a policy that requires you to have a prerequisite policy. This is from when we switched from directly using the toaster library (#1322) and now go through platform utils. The toaster library support an error object but platform utils does not. 
Asana Task: https://app.asana.com/0/1201259213711784/1201780427940282/f
- **src/app/organizations/manage/policy-edit.component.ts:** Platform utils expects a string/string[] so I send it the message property from an error so that it's get's a descriptive message of what went wrong. 
Ensure that you get a toast error when attempting to enable a policy that can't be enabled.
=> Send in error message for toast.

src/app/layouts/navbar.component.html
> Update all `help.bitwarden.com` and `bitwarden.com/help/article/*` to the new `bitwarden.com/help/*` URL pattern
- **navbar.component.html**: Updated URL to new pattern
- [jslib - [Help] Update links to new pattern](https://github.com/bitwarden/jslib/pull/658)
- Make sure URL links don't 404 and take you to the correct page
=> [Help] Update links to new pattern

src/app/vault/ciphers.component.ts
Fix https://github.com/bitwarden/web/issues/1420.
The `userHasPremiumAccess` property was being set before the sync was completed, so it was defaulting to `false`. This was hiding the Copy Verification Code menu item until the user navigated away from and back to the vault component.
- `src/app/vault/ciphers.component.ts` - move the premium check into `load`, add a comment to discourage use of `ngOnInit` in the future.
Confirm bug is fixed.
=> Fix Copy Verification Code not showing after first log in

webpack.config.js
Fix the dev server csp headers.
`req.url` was returning just the paramters. We want the full url path, which is offered by `originalUrl`
N/A
=> Fix dev server connector headers

src/app/tools/import.component.html
Pulls in the changes made in https://github.com/bitwarden/jslib/pull/707, https://github.com/bitwarden/jslib/pull/708 and https://github.com/bitwarden/jslib/pull/711
Updated copy for Dashlane JSON and CSV importer
Asana task: https://app.asana.com/0/1200578627114106/1201930330138516/f and https://app.asana.com/0/1153292148278596/1200559746179756/f
- **jslib:** Pull in changes from https://github.com/bitwarden/jslib/pull/707, https://github.com/bitwarden/jslib/pull/708 and https://github.com/bitwarden/jslib/pull/711
- **src/app/tools/import.component.html:** Updated copy for Dashlane JSON and CSV importer
Details for testing the importer can be found on the PR's
=> Pull in Dashlane and Myki importer

src/app/components/premium-badge.component.ts, src/app/oss.module.ts, src/app/settings/emergency-access-add-edit.component.html, src/app/settings/emergency-access.component.html, src/app/settings/two-factor-setup.component.html, src/app/tools/tools.component.html, src/app/vault/add-edit.component.html
Adds a new premium-badge component using the new styling. The isPremium logic is moved into the component using the new `appUnlessPremium` directive.
Resolves SG-21
Depends on https://github.com/bitwarden/jslib/pull/710
Verify the badges looks as expected and clicking works.
=> Add premium badge component

bitwarden_license/src/app/app.module.ts, bitwarden_license/src/app/organizations/organizations.module.ts, bitwarden_license/src/app/providers/providers.module.ts, src/app/app.module.ts, src/app/oss.module.ts
SG-131
Depends on https://github.com/bitwarden/jslib/pull/733.
* remove any jslib modules from `app.module`, import `JslibModule` instead
=> [JslibModule] Refactor to use JslibModule

webpack.config.js
Add globals defined by Angular CLI for tree shaking.
https://github.com/angular/angular-cli/blob/0c112e5d915af9f2f30879cea55e41751dbf0f1b/packages/angular_devkit/build_angular/src/webpack/configs/common.ts#L367-L368
EC-110
=> Define Angular CLI globals to support tree shaking

src/app/polyfills.ts, src/app/send/access.component.ts, src/app/settings/change-kdf.component.html, src/app/settings/change-kdf.component.ts, src/services/webPlatformUtils.service.ts
Updates to use the new constants from https://github.com/bitwarden/jslib/pull/723
EC-109
Regression test actions related to KDF.
- Register
- Login
- Change KDF
- Create, modify, access send with password
=> Use the new KDF constants

package-lock.json, package.json
Bump node-forge https://github.com/bitwarden/jslib/pull/722
EC-111
Our normal regression testing should cover this. (Node-forge is used in all jslib clients for cryptographic operations).
=> Bump node-forge

src/app/tools/password-generator.component.html, src/app/tools/password-generator.component.ts
Make desktop app compile and work with latest jslib references caused by username generator. A follow up PR will implement the new username generator.
- Update jslib reference
- password-generator.component.ts - resolve new super dependencies
- password-generator.component.html - rename properties for password generator specific options.
Ensure password generator continues to work as before.
=> Bump jslib and add compatability with username generation

src/app/oss-routing.module.ts, src/app/oss.module.ts
Update jslib to get proper fix for sends, and remove DatePipe from routing module.
Context: https://bitwarden.atlassian.net/browse/PS-141
- **src/app/oss-routing.module.ts:** Remove other fix
- **jslib:** update
=> update jslib and remove date pipe from routing module

src/app/layouts/navbar.component.html, src/app/organizations/vault/vault.component.html, src/app/oss-routing.module.ts, src/app/vault/vault.component.html, src/locales/en/messages.json
Rename "My Vault" to "Vaults"
Resolves SG-27
=> Rename "My Vault" to "Vaults"

src/app/oss-routing.module.ts, src/app/oss.module.ts, src/app/tools/generator.component.html, src/app/tools/generator.component.ts, src/scss/pages.scss
Apply client updates from https://github.com/bitwarden/jslib/pull/753
React to changes from https://github.com/bitwarden/jslib/pull/753
Also, added a "learn more" icon for username types on the generator.
NOTE: I still need to update jslib once https://github.com/bitwarden/jslib/pull/753 is merged.
=> generator updates

.github/workflows/release.yml
Bumping the pinned commit for the download-artifact to bypass the github api issue
- **.github/workflows/release.yml:** action commit bump
=> Bump the download-artifact pinned commit

package-lock.json, package.json
Bumps the Braintree dependency since we have Snyk warnings related to this.
Verify payments works.
=> [EC-161] Bump braintree

src/app/organizations/settings/organization-subscription.component.html, src/app/organizations/settings/organization-subscription.component.ts, src/app/oss.module.ts, src/app/settings/billing-sync-key.component.html, src/app/settings/billing-sync-key.component.ts, src/locales/en/messages.json, src/scss/modals.scss
Adds in Billing Sync management to Organization Subscription page for self-hosted installations.
* **organization-subscription.component**: add in manage billing sync section and modal, with callback to update the data for sync hints
* **oss.module**: add in new component
* **billing-sync-key.component**: Build billing sync key update modal.
* **messages.json**: add billing sync messages
* **modal.scss**: Fixes bug from dark theme rewrite that changed the modal footer boarder to rounded corners.
Test functionality around billing sync key upload. Should match figma definition and allow for create, update, delete, with status updates for sync times.
Requires bitwarden/jslib#770
=> [PS-248] Feature/manage billing sync connection

src/app/accounts/login.component.ts
Fix redirect parameter for login component for families-for-enterprise sponsorships
=> Fix login sponsorship redirect

src/locales/en/messages.json
Add descriptions/context for the A-Z & a-z items.
=> Add description for the A-Z & a-z items

src/locales/en/messages.json
Add description to source string, "Identify and close security gaps in your online accounts by clicking the reports below"
=> Add description to reports message source string

src/app/accounts/two-factor.component.ts
Updated two-factor component to be aligned to [jslib change](https://github.com/bitwarden/jslib/pull/782) to send DeviceId on 2FA email resend code
- **src/app/accounts/two-factor.component.ts:** Added `AppIdService` reference and to the ctor.
When logging in on a new device with email verified and being on the verification code view on any client, on resending the verification code the user should receive the email correctly.
=> [PS-79] Updated two-factor component to align to jslib to send DeviceId on 2FA email resend code

src/app/guards/home.guard.ts, src/app/services/services.module.ts, src/app/tools/generator.component.ts
Consequential changes from https://github.com/bitwarden/jslib/pull/721.
* use new authService.authStatus() method
=> [PS-74] Fix user authentication state checks

src/locales/en/messages.json
Adding description string for 'random'
Add a description for the source string 'random':
"Generates domain-based username with random letters".
=> Update localization description for 'random'

src/app/organizations/settings/billing-sync-api-key.component.html
The name of the component to check a users master password was change and rebasing off of `master` broke ours.
Use new name.
=> Change to new name

src/scss/buttons.scss
Long filter items wrap, when they should truncate.
* Add typical ellipsis-cutoff css to link buttons
=> [euvr] [fix] Truncate long filters

src/app/organizations/guards/permissions.guard.ts
See https://github.com/bitwarden/jslib/pull/791
Waiting on that PR to merge first.
=> [SG-225] Remove BaseGuard

src/app/settings/settings.component.html
> Update the `Settings` label to `Account Settings` for the left hand navigation within the `Settings` flow
> SG-246
- **settings.component.html** `settings` -> `accountSettings` string change
- Make sure left hand navigation within settings flow says `Account Settings`
- Will be 🍒 ⛏️  to `rc`
=> [euvr] Settings -> Account Settings label

src/app/modules/vault/modules/individual-vault/individual-vault.component.ts
Fix inability to add ciphers to vaults.
This was fixed here for org vaults: https://github.com/bitwarden/web/pull/1646
=> [SG-256] Check for null cipher in edit

src/app/modules/vault-filter/components/organization-filter.component.html, src/app/modules/vault-filter/vault-filter.component.html, src/app/modules/vault/modules/organization-vault/organization-vault.component.ts, src/app/organizations/vault/ciphers.component.ts, src/scss/vault-filters.scss
Fixes:
- SG-235 First item in org/vault switcher is showing as all uppercase
- SG-250 Always show organizations 3 dot menu
- SG-254 Items in trash not showing up in Organization vault
- SG-258 Styling of Org name in vault switcher for an account affected by personalOwnership and SingleOrg policies is off
- **src/app/modules/vault-filter/components/organization-filter.component.html:** Fix HTML selectors to fix [SG-258] and remove hover conditions for 3 dot org menu [SG-250]
- **src/app/modules/vault-filter/vault-filter.component.html:** Fix extra padding on bottom of vault switcher
- **src/app/modules/vault/modules/organization-vault/organization-vault.component.ts:** Uncomment out code that was left commented
- **src/app/organizations/vault/ciphers.component.ts:** Pass in deleted filter …
=> [SG-230] Various small vault filter fixes

src/app/modules/vault-filter/components/organization-filter.component.html
Use correct localization string.
This will be cherry picked to rc 
- **src/app/modules/vault-filter/components/organization-filter.component.html:** Switch 'addOrganization' to 'newOrganization'
=> [SG-252] Use correct localization string

src/app/accounts/login.component.ts, src/app/accounts/register.component.ts, src/app/components/organization-switcher.component.html, src/app/modules/vault-filter/components/organization-filter.component.html, src/app/oss-routing.module.ts, src/app/settings/create-organization.component.html, src/app/vault/share.component.html
> Update the Create New Organization component to be free of its `settings` dependencies. Move routing outside of the `settings` scope in order to remove left hand navigation inherited from the `settings` route tree
> SG-247
> Will 🍒 ⛏️  to `rc`
- **login.component.ts**: Updated navigation route
- **register.component.ts**: Updated navigation route
- **organization-switcher.component.html**: Updated navigation route
- **organization-filter.component.html**: Updated navigation route
- **oss-routing.module.ts**: Moved route outside of the `settings` context
- **create-organization.component.html**: Updated UI to match previous router output structure
- **share.component.html**: Updated navigation route
=> [bug:euvr] Create Organization Updates

src/app/modules/vault/modules/individual-vault/individual-vault.component.html
Update the Go Premium callout link, as the location of this page was changed during End User Vault Refresh.
**Will be picked to rc**
=> [SG-257] Update Go Premium link

src/app/organizations/tools/exposed-passwords-report.component.ts
Resolves an old todo we had.
Note: Needs to be cherry picked to `rc`.
=> [SG-267] Exposed passwords report: console error

src/app/accounts/lock.component.ts
PreviousUrl is null when logging in through SSO. Caused by the redirect refactor in the linkable cipher.
=> [SG-279] Fix unlock button not working after logging in through SSO

src/app/modules/vault/modules/individual-vault/individual-vault.component.html
https://bitwarden.atlassian.net/jira/software/projects/SG/boards/34?selectedIssue=SG-290
https://bitwarden.atlassian.net/jira/software/projects/SG/boards/34?selectedIssue=SG-291
https://bitwarden.atlassian.net/jira/software/projects/SG/boards/34?selectedIssue=SG-292
This will be cherry-picked to rc
There are a few bugs from the EUVR initiative that relate to the trash filter.
1. The "Add Item" button is still shown, it should not be
2. The bulk actions for the trash filter are specific, and are not being honored
3. The callout re: the thirty day delete job is missing
This was a pretty simple fix, we changed the name and style of a condition but did not update the template.
=> [fix] Various Trash filter bugs from EUVR

src/app/tools/generator.component.html
The hostname parameter for the simplelogin API should be handled automatically without user input. Remove the user input.
Update jslib.
- **generator html:** Remove the hostname input from simplelogin forwarding service.
=> remove hostname from simplelogin. update jslib

src/locales/en/messages.json
Update the confirmation text of revoking a sponsorship
=> [PS-624] Update Revoke sponsorship text

src/locales/en/messages.json
Update Key Connector error message to make it more generic. Depends on https://github.com/bitwarden/jslib/pull/816. (update: merged and updated)
- **file.ext:** Description of what was changed and why
=> [EC-177] Update Key Connector error message
