bitwarden/web

src/Web/wwwroot/app/vault/views/vault.html

When a folder has no sites, there's a convenient 'add site' button. It would be nice if this was permanent. 
It's tedious to have to select a folder each time, causing at least in my case to forget about the folder selection since it wasn't used on the first site that was added (due to the convenient add site button).

Adding permanent add site button to each folder

---

src/app/vault/vaultAddCipherController.js

SecureNote Type is defined as int not as string, send int in JSON

vaultAddCipherController.js: secureNote Type is int not string

---

package.json

When using VS 2017 node.js integration, npm fails because a host key cannot be validated. Switching to https, provides security and no additional configuration to restore the package.

Change npm to use https for gulp-gh-pages restore.

---

src/app/tools/breach-report.component.html

This PR provide a fix for brokens logos on breach report page :
Depends on PR  [bitwarden/jslib#23](https://github.com/bitwarden/jslib/pull/23)

fix logos in breach report page

---

src/scss/styles.scss

Screenshots attached. Should be pretty clear.
bootstrap disables this behaviour by default.

enable clear button in search input types

---

src/app/vault/add-edit.component.html

This fixes https://github.com/bitwarden/browser/issues/847 by adding the `trackBy` option to the `ngFor` directives used for URIs and custom fields.
https://github.com/bitwarden/jslib/pull/27 is required.

Fix disappearing fields

---

src/app/tools/weak-passwords-report.component.ts

* Summary
Stops showing score 3 passwords in Weak Passwords Report page.
https://vault.bitwarden.com/#/tools/weak-passwords-report
* Reason
In zxcvbn library that scores the password, score 3 is considered "safely unguessable" (c.f. https://github.com/dropbox/zxcvbn#usage )
Showing too many passwords in the list distracts users and prevents from focusing on really weak passwords.

Stop showing score 3 passwords as weak passwords

---

src/app/organizations/vault/add-edit.component.ts
src/app/vault/add-edit.component.html
src/app/vault/add-edit.component.ts

> Implement the ability for organizational admins to assign ownership during clone item flow. This can be used as a roundabout method for "unsharing" organizational items back to personal vaults.
- **organizations/add-edit.component.ts**:  added function for determining ownership visibility and adjusted save function override to call proper api for adding a cipher when cloning to personal vault (non-admins will NOT be able to assign ownership)
- **add-edit.component.html**: changed direct conditionals to call allowOwnershipAssignment function
- **add-edit.component.ts**: added function for determining ownership visibility

Allow organizational admins to assign clone ownership

---

src/app/organizations/manage/policy-edit.component.html
src/app/services/services.module.ts
src/app/tools/password-generator.component.html
src/app/tools/password-generator.component.ts
src/app/vault/add-edit.component.ts

>Make sure the Password Generator enforces the specific rules set by an Organization for password generation. In the case of multiple Organizational rules, apply the stricter option.
- **policy-edit.component.ts**: Added basic min/max restrictions for the three input fields to deny saving negative numbers or numbers outside the allowed ranges within the Password Generator
- **services.module.ts**: Added the `policyServer` dependency into the `passwordGenerationService`
- **password-generator.component.html**: Adjusted the `min-number` and `min-special` field to mirror how the `length` field operates and adjust the `disabled` property for each checkbox based on the enforced policy options
- **password-generator.component.ts**: Added methods to focus the field(s) when a `change` event …

Enforce Password Generator Policy Options

---

src/app/services/services.module.ts
src/app/tools/password-generator.component.html
src/locales/en/messages.json

> While an organizational password generator policy is enabled, alert the user that all/some settings are being adjusted.
- **password-generator.component.html**: Added `app-callout` banner and made visible when a policy is in effect
- **messages.json**: Added `passwordGeneratorPolicyInEffect` string

Show policy in effect banner for password generator

---

src/app/accounts/accept-organization.component.ts
src/locales/en/messages.json

If the invite to org fails for the user and a server error message is available, show them why.

Show reason for invite accept failure if available

---

src/app/accounts/register.component.html
src/app/accounts/register.component.ts
src/app/organizations/manage/policy-edit.component.html
src/app/services/services.module.ts
src/app/settings/change-password.component.html
src/app/settings/change-password.component.ts
src/locales/en/messages.json

> Enforce Organizational policies regarding master password strength during the Change Password and Register Account (for Org Invite) flows. 
- **register.component.html**: Added `app-callout` banner to alert users of policy restrictions that will be enforced during account creation within the org acceptance flow
- **register.component.ts**: Added logic to retrieve and enforce the organization's policy.  The above banner will be shown when applicable and on submit, the password will be evaluated. If there are no policies to evaluate, it is skipped and normal operations resume.
- **policy-edit.component.html**: Added a minimum value of 8 for the password length field. Users can leave the field empty if desired.
- **change-password.component.html**: Added `app-callout` banner to alert users …

Enforce Master Password Policies (Change/Register)

---

src/app/accounts/register.component.html
src/app/accounts/register.component.ts
src/app/organizations/manage/policy-edit.component.html
src/app/organizations/manage/policy-edit.component.ts
src/app/settings/change-password.component.html
src/app/settings/change-password.component.ts

> Make the complexity score requirement less cryptic: add readable display strings for different scores
- **register.component.html**: Updated string param to pull result from the `getPasswordScoreAlertDisplay()` function
- **register.component.ts**: Fixed lint warning with variable creation. Added helper method to return the correct display string for password scores
- **policy-edit.component.html**: Changed UI field to a dropdown and used the `passwordScores` list to populate it
- **policy-edit.component.ts**: Created `passwordScores` list for use in displaying readable scores
- **change-password.component.html**: Updated string param to pull result from the `getPasswordScoreAlertDisplay()` function
- **change-password.component.ts**: Added helper method to return the correct display …

Update complexity score display

---

src/app/organizations/manage/policy-edit.component.html
src/app/organizations/manage/policy-edit.component.ts
src/app/tools/password-generator.component.html
src/locales/en/messages.json

> Add missing components for passphrase policy. Use existing data structures/patterns to implement a shared password generator (password/passphrase)
- **policy-edit.component.html**: Added default types dropdown along with fields needed to enforce passphrase generation (minimum number of words, capitlize, and include numbers)
- **policy-edit.component.ts**: Created default types list and updated the loading/submitting of password generator policy settings to include passphrase options.
- **password-generator.component.html**: Updated existing fields to respect potentially enforced options for passphrase generation
- **messages.json**: Added new strings

Enforce passphrase policy

---

src/app/accounts/lock.component.ts
src/app/app.component.ts
src/app/services/services.module.ts
src/app/services/unauth-guard.service.ts
src/app/settings/options.component.html
src/app/settings/options.component.ts
src/locales/en/messages.json
src/services/htmlStorage.service.ts

> Update the web application to use the updated `VaultTimeoutService` to allow for logging out on an interval timeout.  Allow users to choose what action takes place when the timer expires (Lock vs Log out)
- **jslib**: Update from 31a2574 -> 28e3fff
- **lock.component.ts**: Updated import. Updated constructor. Updated super call.
- **app.component.ts**: Updated import. Updated constructor. Updated necessary calls to the new `vaultTimeoutService`
- **services.module.ts**: Updated imports. Updated instantiation for new name and added log out callback action. Updated dependencies to use new abstraction/service.
- **unauth-guard.service.ts**: Updated import. Updated constructor. Updated necessary calls to the new `vaultTimeoutService`
- **options.component.html**: Updated name dependencies. …

[Auto-Logout] Implement upstream changes

---

src/app/app.module.ts
src/app/organizations/vault/add-edit.component.ts
src/app/organizations/vault/ciphers.component.ts
src/app/organizations/vault/vault.component.html
src/app/organizations/vault/vault.component.ts
src/app/services/event.service.ts
src/app/tools/cipher-report.component.ts
src/app/vault/add-edit.component.html
src/app/vault/bulk-restore.component.html
src/app/vault/bulk-restore.component.ts
src/app/vault/ciphers.component.html
src/app/vault/ciphers.component.ts
src/app/vault/groupings.component.html
src/app/vault/vault.component.html
src/app/vault/vault.component.ts
src/locales/en/messages.json

Incorporate the new APIs for soft deleting and restoring cipher items into the web vault client. This includes a UX that presents a new logical "Trash" bin under "Favorites" on _My Vault_ view and under "All Items" in the _Organization_ view.
Easy to local and use **Trash**. When deleting an item anywhere in the interface (from the vault list, bulk action or in the edit/detail view) this item will now be "soft deleted" (essentially moved to the Trash). When performing searches, etc. the scope of that search will always either be "Trash" or anything else (when selected). Context will not cross between items in Trash from the rest of the vault, including "All Items".
* Context under Trash changes to show delete options as "Permanent" vs. just Delete.
* A new option to "Restore" selected …

[Soft Delete] - Added trash and related functionality to web vault

---

src/locales/en/messages.json

Updated deleted messages for the toast displayed when an item is really soft-deleted (sent to trash) vs. permanently deleted.

[Soft Delete] - Deleted message (sent to trash)

---

src/app/organizations/manage/people.component.ts

Causes errors on the initial page load.

Null check `allUsers`

---

package.json

This additions fix the `npm WARN issues`:
- npm WARN bitwarden-web@2.13.2 No repository field.
- npm WARN bitwarden-web@2.13.2 No license field.

fix: package.json info

---

package-lock.json
package.json
webpack.config.js

**What is fixed**
Warning and error from npm and build log:
1. warning
`warning: Since webpack v4 the extract-text-webpack-plugin should not be used for css. Use mini-css-extract-plugin instead.`
2. error
`Entrypoint undefined = extract-text-webpack-plugin-output-filename...`
New plugin implementation documents:
[https://webpack.js.org/plugins/extract-text-webpack-plugin/#usage](https://webpack.js.org/plugins/extract-text-webpack-plugin/#usage)
[https://webpack.js.org/plugins/mini-css-extract-plugin/#advanced-configuration-example](https://webpack.js.org/plugins/mini-css-extract-plugin/#advanced-configuration-example)

fix: webpack.config.js plugin

---

src/app/organizations/manage/collections.component.html
src/app/organizations/manage/collections.component.ts
src/app/organizations/manage/groups.component.html
src/app/organizations/manage/groups.component.ts
src/app/organizations/manage/people.component.html
src/app/organizations/manage/people.component.ts

> To combat potential performance issues with larger organizations, add pagination to the Users (People), Groups, and Collections management.
- Added `infiniteScroll` UI components
- Added logic to handle loading more list items - follows precedent set by the `ciphers.component`
- Set page size to 100 for Users, Groups, and Collections

[Paging] Added for Organization Users, Pages, and Collections

---

src/app/app.component.ts

Close any alerts that might be open when locking the client after inactivity, before rerouting back to the home screen
Closes #535

Closed alerts on lock

---

src/app/tools/password-generator-history.component.html
src/app/vault/add-edit.component.html
src/app/vault/ciphers.component.html

According to: https://github.com/bitwarden/desktop/pull/490
Replace the "copy value" icon with `fa-clone`.

Consistent: Replaced the clipboard icon with a clone icon to improve UX

---

src/app/organizations/manage/collections.component.ts
src/app/organizations/manage/groups.component.ts
src/app/organizations/manage/people.component.ts

Fixes #583 
This was originally introduced by #539 (paging) which caused, on initial render, the `this.users`, `this.collections` and/or `this.groups` arrays to not yet be initialized (were `undefined` or `null` and therefore caused JavaScript exceptions). This didn't impact other functionality because they would later become initialized and paging would work appropriately. However, if you clicked on a category/filter that was empty, and then tried to click "Add/Invite", etc., it would cause a re-render/init call based on Angular's 2-way bindings (for `isPaging()` and `reload()`) and these arrays would once again be `null` and/or `undefined` causing an exception and failing to render the component in the modal body once launched.

Fix modal-body div missing #583

---

src/services/htmlStorage.service.ts

resolves #629
As @vincentsalucci discovered in #629, we are hitting `sessionStorage` limits provided by the browser when users have large vaults. This PR switches from using sessionStorage to using a basic in-memory `Map<string, string>`, which effectively gives us the same functionality without the need to utilize disk and be subject to the browser's limitations.

switch from session storage to memory storage

---

src/services/htmlStorage.service.ts

Recently I changed this storage service to use memory storage instead of session storage to address the limitations with session storage lengths. This was probably a bit too aggressive since the only keys were data grows large is in the vault. This change adds checks for only using memory storage for specific vault data keys so that other keys can still use session storage. This prevents things like the user being logged out completely on page refresh.

only use memory storage for vault data keys

---

src/app/settings/payment.component.html

Fixes #649 
The "Learn More" link icon attached to the CVC input of the payment component doesn't work. Instead of opening the link, clicking this icon applies focus to the CVC input element.
The CVV help link being a child element of a `<label>` with a `for` attribute was causing clicking the link to instead focus on the label's bound input. 
Separating the link and the label resolves this issue without breaking the intended functionality of a `<label for="">`

fixed the cvv learn more link in the payment component

---

src/app/services/services.module.ts
src/services/webPlatformUtils.service.ts

Fixes and closes #653 
This is caused by the Edge browser detection from the user-agent string provided by the Edge browser, which Microsoft changed to use the `Edg/` token vs. the `Edge/` token previously used to help differentiate over confusion from the prior, Trident based IE Edge browser.

653 - fix user agent detection for Edge

---

src/app/organizations/settings/change-plan.component.html
src/app/organizations/settings/change-plan.component.ts

Changing plan & product information to use enums broke the default selection of "Families" when upgrading a free org
Passing the correct enum to the organization plans component from the change plan component fixes this, and Families is selected by default

Default selection plan upgrade fix

---

src/app/organizations/manage/policies.component.html
src/app/organizations/manage/policies.component.ts
src/app/organizations/manage/policy-edit.component.html
src/app/organizations/manage/policy-edit.component.ts
src/locales/en/messages.json

>  Add a new enterprise policy that requires users within an organization to log in with SSO. 
- **policies.component.ts**: Created function to dynamically add `RequireSso` policy if necessary.  Passed along the `policiesEnabledMap` to the Edit modal.
- **policy-edit.component.html**: Added new callout for the `RequireSso` policy
- **policy-edit.component.ts**: Added new input variables required for pre-validation.  Adjusted `submit` function to first call the `preValidate` function.  For the `RequireSso` policy, the `SingleOrg` policy must be enabled in order to submit an enabled policy.
- **messages.json**: Added strings

[Require SSO] Enterprise policy adjustment

---

src/app/app.component.ts
src/services/webPlatformUtils.service.ts

Resolves and closes #681 
Blamed on: https://github.com/bitwarden/web/pull/465 (introduced the issue)
Exposed by: https://github.com/bitwarden/web/pull/572 (caused the issue to surface)
Fix: Reference the already transpiled dist version of the sweetalert2 module vs. using the src version which skips compilation (and we're not using Babel, etc. for transpiling vendor libraries).

Use properly transpiled SweetAlert2 lib

---

src/app/organizations/manage/policy-edit.component.html
src/locales/en/messages.json

> UI Updates: Owners and admins are exempt from organization removal during policy saving for the following policies: **2fa, Single Org**. Owners and Admins are exempt from policy enforcement for **Require SSO** policy.
- **policy-edit.component.html**: Added `warning` callout for **RequireSso** describing exemption rules.
- **messages.json**: Updated messages to include exemption rules.

[Exemption] Updated policy messages

---

src/app/vault/ciphers.component.html

This adds a 'Copy Username' button above the 'Copy Password' button in the dropdown for individual entries in the safe. This matches the capabilities of the desktop app, where you can right-click on any entry and get options for both 'copy password' and 'copy username'.
Currently the only way to easily copy the username is to manually highlight the name under the entry name. Double-clicking or triple-clicking to highlight the entire username often isn't suitable either, because it usually results in extraneous whitespace being copied.

Add 'Copy Username' button

---

src/locales/en/messages.json

Align messages for item delete across platforms. Mobile's example of "Do you really want to send to the trash?" makes it clear that an item is only going to be soft deleted, so that was used everywhere.
* **messages.json**: Updated the `deleteItemConfirmation` message to Mobile's message.

Use mobile's trash message for item delete

---

src/app/accounts/two-factor.component.ts
src/app/services/services.module.ts
src/services/webPlatformUtils.service.ts

> During the SSO auto provision flow - if an org has 2fa required and the user's account is brand new, the `OrgIdentifer` was not being properly passed along to the `set-password` component.  This resulted in the user's organization status remaining in an `invited` state.
- [Server - 996](https://github.com/bitwarden/server/issues/996)
- **jslib**: Update from 6563dcc to d9d13bb
- **two-factor.component.ts**: Added query parameter `identifier` to the route data. 
- **webPlatformUtils**: Added new interface method. Web supports `secureStoreage` via `memoryStorage.service`
- **services.module**: Added `platformUtilsService` to the `crypto.service`

[Bug] Update 2fa navigate action to pass along Org Identifier

---

src/connectors/sso.ts

Currently, SSO sign on from the browser extension signs into web. It should open a webpage to allow for specification of SSO settings, complete SSO, and redirect to the extension for vault decryption.
* **sso.ts**: state string was changed to include the organization identifier, but this broke the pivot we were using for web vs browser sign-ons. This is a quick fix for this, but it may be that a contains is better suited or even moving/removing identifier.  I don't really have the expertise in the feature to understand the implecations of changing the state string. It's clearly pretty fragile.

WIP: dirty fix to SSO web vs browser redirect logic split

---

src/app/tools/exposed-passwords-report.component.ts
src/app/tools/inactive-two-factor-report.component.ts
src/app/tools/reused-passwords-report.component.ts
src/app/tools/unsecured-websites-report.component.ts
src/app/tools/weak-passwords-report.component.ts

Resolves and closes #699 
After the introduction of soft-delete (the trash bin) feature, we've seen some functions, features and tools still continue to use soft-deleted items, such as reports. This change filters deleted items currently in the Trash bin from being included in this reporting.
Future Consideration: Perhaps a new or special report that compares deleted items from the trash, etc.; however that is out of scope for this change.
This should wait to be merged until after our upcoming release 11/12/2020 to ensure adequate testing time before release.

Exclude deleted items from any/all reports

---

src/app/accounts/sso.component.ts
src/connectors/sso.html
src/connectors/sso.ts
src/locales/en/messages.json

This is done after the authResult handoff message is delivered to the
extension. It is not possible to close the window from javascript as
closing a window is limited to the script that opened it.
If we maintain a reference to the web window, it should be possible to
subscribe to the authResult message and close the web windows from the
browser.
updates the web sso logon page to indicate it is OK to close.

Update web sso content to indicate window OK to close

---

src/app/tools/import.component.html

The current method of using FF importer is outdated. Firefox has a native exporter which is convenient to use. 
Added hyperlink to https://bitwarden.com/help/article/import-from-firefox/

Updated Firefox Import Instructions

---

src/app/organizations/manage/policies.component.ts
src/app/organizations/manage/policy-edit.component.html
src/app/organizations/vault/add-edit.component.ts
src/app/services/event.service.ts
src/app/vault/add-edit.component.ts
src/locales/en/messages.json

> When the Personal Ownership policy is enabled, require all org users (who are not Owners or Admins) to save newly created or newly cloned ciphers to an organization/collection(s). Add ability to correctly view Policy modifications in the Event Logs section.
- **policies.component.ts**: Added new policy to the policies array. Added handling of query param string from event message: will properly pull open the modified policy.
- **policy-edit.component.html**: Added app callout for exemption status
- **Organization/add-edit.component.ts**: Updated constructor. Adjusted `allowOwnershipOptions` to include logic check to keep it clear which org is selected (even if only one is available)
- **event.service.ts**: I wanted to keep this lightweight to mimic the other implementations, but had to …

[Policy] Personal Ownership

---

src/locales/en/messages.json

> Fix small casing issue with the personal ownership error message
- **messages.json**: Lowered case for `option`

[Policy] Personal Ownership error message

---

README.md

Hi Bitwarden, 
I am working on a feature for this repo, and I ran into some issue running the [app against production](https://community.bitwarden.com/t/catch-and-prompt-user-of-potential-duplicate-passwords-on-import/14955/14). I found solutions to my issues ([major one here](https://github.com/bitwarden/web/issues/666)), and I wanted to update the README so others don't run into the same issues.
Changes:
- Noted Node.js version can only be up to 13.9.0 because of SCSS version support
- Added events url to reflect how services.module.ts actually looks
- Added instructions for how to use the correct npm command for running the app against production
Please let me know what you think about these changes, and if there is anything I should add or remove.
Best,
Josh

Updated readme to note how to run the app against production

---

package.json
src/app/services/services.module.ts
src/connectors/sso.ts
src/services/htmlStorage.service.ts
tslint.json

Use the default consoleLogService. jslib is moving toward requiring clients to specify a console logger. This change also includes the `browser-process-hrtime` dependency
* **packages.json**: Add new dependency
* **services.ts**: Add new required ConsoleLogService definition

Add ConsoleLogService dependency from jslib

---

src/app/organizations/vault/ciphers.component.ts
src/app/vault/ciphers.component.html
src/app/vault/ciphers.component.ts

Offering copying of totp from context menu covers only one method-of-use. Offering another quick-copy button on the tabs/cipher list view closes this gap.
* **organizations/ciphers.component.ts**: Include totpService now required by parent.
* **cipher.component.html**: Include Copy Verification Code in context menu if totp is present
* **ciphers.component.ts**: Get totp from totpService, add to clipboard, and notify of hidden field revealed.
Waiting on bitwarden/jslib#225

Add totp copy to clipboard button to cipher view

---

src/app/vault/attachments.component.html

Attachments with long file names go beyond the window. #695

---

src/app/organizations/manage/policy-edit.component.ts
src/locales/en/messages.json

> Do not allow users to **disable** the `SingleOrg` policy when the `RequireSso` policy is **enabled**.
- **policy-edit.component**: Added explicit check for when saving the `SingleOrg` policy to check for the above condition.
- **messages**: Added new error string

[Policy] Single Org dependency chain

---

src/app/vault/groupings.component.html

Does a little bit of reversal on the removal of carets from *all* items (see PR https://github.com/bitwarden/web/pull/410), and instead uses an icon for the item OR a caret (if expandable) for folders and collections. Needed to remove some of the formatting based on the `.carets` class as well in this instance because we need things to align with the stuff higher up.

show caret or icon, not just "blank" space

---

.github/workflows/build.yml

Moving the CI pipeline from AppVeyor to GitHub Actions. Adding in Docker Content Trust as well. 
:warning: Without the repo secrets below, the `Build:ubuntu` task will fail and the docker image will not be built or published.
- .github/workflows/build.yml
- DOCKER_USERNAME
- DOCKER_PASSWORD
- DOCKER_WEB_KEY
- DOCKER_DELEGATION_KEY
- DOCKER_CONTENT_TRUST_REPOSITORY_PASSPHRASE (passphrase for the DOCKER_DELEGATION_KEY)
- Clean runs for all 3 jobs without being master/release (reference: https://github.com/joseph-flinn/web/actions/runs/431530610)
- `master/release` tasks model `server` project so should work with the above secrets added. If desired, I can fully test these by setting up Docker Content Trust and pushing to my personal container registry.

Moving appveyor to actions

---

src/app/vault/add-edit.component.html

Closes #531. Cipher view modal's URI match detection selector is not handling overflow properly and pushing the URI delete button off the modal.
This change handles overflow properly. Selecting the modal still displays the full text.

Hide match uri overflow

---

src/app/vault/add-edit.component.html
src/locales/en/messages.json

> To clear up any confusion while the `Personal Ownership` policy is enabled and in effect, a banner has been added to the `add-edit` component. Mimic the password generator banner.
- **add-edit.component.html**: `app callout` banner added to the top of the component
- **messages.json**: added banner string

[Policy] Personal Ownership banner

---

src/app/send/add-edit.component.html
src/app/send/add-edit.component.ts
src/locales/en/messages.json

- Added descriptions under most fields to give more context on what each Send option does on add/edit.
- Added client messages about premium being required when trying to create sends of type "File".
- "Text" type is default whenever not premium.

ui updates for send add/edit component

---

src/app/organizations/manage/policy-edit.component.html
src/app/organizations/manage/policy-edit.component.ts
src/locales/en/messages.json

> Bring some clarity to what is happening when enabling the `Personal Ownership` policy.  Adjust the checkbox description to describe the action being taken.
- **policy-edit.component.html**: Use new `getCheckboxDesc` to properly retrieve the enable checkbox text based on the policy type being edited
- **policy-edit.component.ts**: Added `getCheckboxDesc` that will return a different string based on the Policy Type being edited
- **message.json**: Added new string

[Policy] Update Personal Ownership checkbox description

---

src/app/send/add-edit.component.ts
src/app/settings/change-password.component.ts
src/app/settings/emergency-access.component.ts
src/app/settings/tax-info.component.ts
tslint.json

1. Ran the tslint fixer over a few files to remove new trailing comma warnings from the new linter rule specifying them
2. Added another tslint rule to keep the fixer from automatically wrapping single property lambda functions in parenthesis

Fixed trailing comma lint warnings

---

src/app/accounts/accept-emergency.component.html

Remove the grantee's email from the accept emergency contact invite page to avoid confusion.

Remove grantee email from accept-emergency component

---

src/app/settings/premium.component.html
src/app/settings/premium.component.ts

https://github.com/bitwarden/server/pull/1087
@thekazian discovered during testing that sales tax isn't being charged on Premium signups
1. Reworked the `premium` component & template to show subtotal, sales tax, and total.
2. Relocated price information on the `premium` component template to below card information similar to the move that was made on the organization signup screen.

Sales Tax for Premium signups

---

src/app/organizations/manage/entity-users.component.html
src/app/organizations/manage/policies.component.html
src/app/organizations/manage/policies.component.ts
src/locales/en/messages.json

Fixed various UI issues with Permissions reported by @clayadams5226 during testing
1. If someone has a custom permission, when the admin goes to the user access screen (Manage > Collections > Users) Custom doesn't show up next to the user. It's just blank
2. If I have the policies permission, but not the portal permission, I'm still able to access the portal from the policies page (although I can't make any changes.)
3. The SSO permission is displayed as "Sso" should it all be caps?

fixed various Permissions UI issues

---

src/app/settings/create-organization.component.ts
src/app/settings/organization-plans.component.html
src/app/settings/organization-plans.component.ts

This PR fixes a few regressions on the organization create page:
- Pre-select product/plan based on `plan=` query parameter.
- Add "7 days free trial" line to enterprise product bullet list
- Set product and plan from free/families to Teams whenever selecting "ownedBusiness" checkbox
Enhancement:
- Default "ownedBusiness" to true if `plan=teams` or `plan=enterprise`.

fixes to plan/pricing page

---

src/app/accounts/two-factor.component.ts

When two-factor authentication is enabled, and you are not "remembered" from a previous session, we don't handle the `emergencyInvitation` token properly.
When I added the handler for the `login.component.ts` in https://github.com/bitwarden/web/pull/707, I forgot to do the same changes to `two-factor.component.ts`.
Resolves https://github.com/bitwarden/web/issues/789.

Fix emergency access confirm not working with two-factor enabled

---

src/app/vault/ciphers.component.ts

Fix copy buttons disabled unless TOTP present. (same bug as bitwarden/jslib#1525)

Fix context copy buttons work only with TOTP present

---

src/app/settings/emergency-access.component.html

Update learn more more link of Emergency Access 
Replaced the current link with https://bitwarden.com/help/article/emergency-access/
Fix for #793

Update learn more link for Emergency Access

---

src/app/settings/emergency-access-add-edit.component.html

The help link for user-access incorrectly linked to the wrong page. Changed to the correct link.

Update emergency access user-access link

---

src/app/vault/add-edit.component.html

Fix #712 - some buttons on the add-edit page were not accessible when tabbing through elements. The issue correctly identified that this is required by web accessibility guidelines. (See issue for relevant links)
Remove `tabindex=-1` from the relevant elements.
I have tested this in Chrome and all elements now appear to be accessible via tab, including those that were raised in the issue report.

make inline buttons accessible with tab button

---

src/app/vault/add-edit.component.html
src/scss/styles.scss

Fix #713: when tabbing through elements, not all elements have a clear outline/shadow to indicate that they have focus. This is required by WCAG.
I inspected each of the elements identified in the issue and grouped them as follows:
* `.btn-outline-secondary`: sets `box-shadow` on focus, but uses a colour with poor visibility. Changed so that it uses the primary colour for `box-shadow`.
* `.btn-link`: does not set any `box-shadow` or `outline` on focus. Changed to set `outline` on focus.
* `.list-group-item`: sets `outline` on focus, but this is partially obscured by other `.list-group-item`s nearby. Changed to set `z-index` on focus so that it's always on top.
* `<a>` items above text input: sets `outline` on focus, but this is partially obscured by the nearby text `input`. Changed to …

Clearer keyboard focus on input elements

---

src/services/webPlatformUtils.service.ts

Fix #703. Microsoft Edge has added U2F support but we still had it disallowed in our code.
Add Edge to the list of browsers that support U2F in `webPlatformUtils.service`.
I couldn't find any clear statement as to whether the Edge mobile app supports U2F - a quick test on my Android (using demo.yubico.com) suggests it doesn't. Therefore I have only enabled U2F support on the desktop Edge browser.
Incidentally, Chrome is the only mobile app that `webPlatformUtils` recognises as supporting U2F. However, in my testing, the `u2f.js` api we use rejects Chrome mobile immediately as not being supported. And it's not clear from our [help documentation](https://bitwarden.com/help/article/setup-two-step-login-u2f/) whether we support web vault U2F on mobile devices at all. I'm mentioning it for …

Allow U2F on Edge

---

src/app/settings/emergency-access-confirm.component.html

This reverts commit 8449cdca75d3309995adc5a153f917a037eb034b.
This seems to actually have been the appropriate help link regarding the fingerprint phrase for verification which is used in several places including Org Invites, Emergency Access, etc.

Revert "Correct URL to emergency access doc (#805)"

---

package-lock.json
src/app/services/services.module.ts

While playing with Sends in web, they were giving the wrong webvault URL. This change fixes that issue and should only impact development environments.
* **services.module.ts**: Uses the default dev webvault url as we do in `apiService.SetUrls` just below this change.
This should have a minimal impact, but please test SSO needs to be validated as webVaultUrl is used for the return address from sso.

Set WebVaultUrl if dev

---

src/app/app.module.ts
src/app/organizations/vault/attachments.component.ts
src/app/settings/emergency-access-attachments.component.ts
src/app/settings/emergency-access-view.component.html
src/app/settings/emergency-access-view.component.ts
src/app/vault/attachments.component.html
src/app/vault/attachments.component.ts

We currently have no way to view attachments in the Emergency Access view mode. This PR adds a dropdown option to view Attachments, which follows the same design patterns we have in the rest of the vault.
- **emergency-access-attachments.component.ts**: New class extending base Attachments component, it overwrites `init` to prevent loading attachments from the local vault, and marks it as `viewOnly`.
- **emergency-access-view.component.ts**: Added handler for opening attachments view.
- **attachments.component.html**: Added support for `viewOnly` attribute.
> We will have to make sure nothing breaks in the emergency-access-attachments component, since it overwrites `init` we could accidentally break things when we modify the base component.
Resolves: …

Add support for viewing attachments in emergency access

---

src/app/organizations/manage/policies.component.ts
src/app/organizations/manage/policy-edit.component.html
src/app/send/add-edit.component.html
src/app/send/add-edit.component.ts
src/app/send/send.component.html
src/app/send/send.component.ts
src/locales/en/messages.json

Depends on bitwarden/jslib#259
Implements web policy editor enabling of `DisableSend` policy. This policy disallows users of an organization from creating or editing Bitwarden Sends. Delete is still allowed.
* **policies.component/policy-edit.component**: add DisableSend policy to the list of policies
* **send/add-edit.component**:  make all inputs either disabled or readonly (prefer readonly) if disable send policy is in effect. Also display an app-callout at the top of the modal and disable the save button. This had to be done with a second button due to the loading effect on the first being tied to the button's disabled state.
* **Send.component**: Add banner warning about sends being disabled. Disable the create button
* **messages.json**: messages relating to disable send policy
Need …

Implement disable send policy

---

src/app/send/add-edit.component.html
src/app/send/send.component.html

Add toggle password visibility to Send add-edit component.
This also fixes an oversight to DisableSend policy where disabled send environments still shows remove password link.
* **add-edit.component.html**: add input-group for password and visibility toggle. wire it up to jslib toggler changes. Password formatting changes match existing Login cipher password element
* **send.component.html**: Do not show remove password link if DisableSend is in effect.
* can show/hide password for both new and existing sends for both has and does not have passwords.
* note, we don't know the password (it's used for authentication) so the old password is not visible in edit mode
* The remove password link does not show up if send is disabled by a policy the user belongs to.

Add show hide password to send

---

src/app/send/add-edit.component.html
src/app/send/add-edit.component.ts
src/locales/en/messages.json

Some general send feedback from the last product team meeting:
- Add option to copy share link to clipboard on create/edit save event.
- Add helper text explaining "name", "text", and "file" fields further.
- Change "type" input from select list to radio button list.
NOTE: we will probably need to propagate these changes down to other clients where appropriate.

send UX improvements

---

src/app/send/send.component.ts

> Recent `jslib` changes require an update to the `web:send.component.ts - ngOnInit()` function. Pull the latest `jslib` and fix any breaking changes.
- **jslib**: Updated to `ee164bebc65aa56e41a122eb4ece8971eb23119b`
- **send/send.component.ts**: Updated import grouping to fix lint warnings. Overloaded `ngOnInit` function to call the now-removed `load` function once the super has completed. This restores the previous functionality.

[Send] Update jslib and init function

---

src/app/organizations/tools/import.component.ts
src/locales/en/messages.json

Fix #824:
> Organization import is not visually distinct from personal import and it easy to accidentally import personal items into an organization.
Add a confirmation dialog when importing data to an organization.

Add warning when importing data to organization

---

src/app/settings/emergency-access.component.ts

Fix #828: 
> Attempting to approve an Emergency Access request from a Bitwarden account that has nothing set in their Name field will show __$1__ as the name.
Evaluate `details.name || details.email` instead of just `details.name`. This is done everywhere else in this component but looks like it was just missed in this case.

Fix emergency access grantee name

---

src/app/organizations/tools/import.component.ts
src/app/services/services.module.ts
src/app/tools/import.component.html
src/app/tools/import.component.ts
src/locales/en/messages.json

Improve import error messages so that users can identify problem items easier.
Errors are currently shown in the format below. 
We say that this index number refers to the index of the CSV. It actually refers to the index of the item in the `importResult.ciphers[]`, `importResult.folders[]` or `importResult.collections[]` arrays (as applicable). For ciphers this will mostly correspond to the CSV index number, with some adjustments, but not always.
One suggestion was to provide the line number in the import file. However, I think it's better to show some actual item details so that users don't have to dig through the import file to identify it. (This is also easier than trying to match the item object with the unparsed import file.)
A user also requested that the error is more "permanent" …

Improve import error messages

---

src/app/send/add-edit.component.html
src/locales/en/messages.json
src/scss/styles.scss

A couple of rogue commits to bring web Send up to speed with some UX changes made while developing clients.
1. Added a toggle to show/hide options. This involved wrapping the inputs and header in divs, which has created a pretty overcomplicated diff.
2. Changed "Send **L**ink copied" toast message to read "Send **l**ink copied"

Web send updates

---

src/app/tools/inactive-two-factor-report.component.ts

Version 1 of 2fa.directory API is [deprecated](https://github.com/2factorauth/twofactorauth/blob/master/API.md#version-1-deprecated-warning).
[Version 2](https://github.com/2factorauth/twofactorauth/blob/master/API.md#version-2) provides an endpoint which only returns services with TOTP.
The result should be much more accurate because the result only contains services that provide TOTP (and not only software 2FA).

Use v2 of 2fa.directory API

---

src/app/layouts/navbar.component.html
src/app/send/add-edit.component.html
src/app/send/send.component.html
src/locales/en/messages.json

> Finish some final cleanup of the components used in `Send` to match other platforms.
- **navbar.component.html**: Updated hardcoded string to string resource.
- **add-edit.component.html**: Moved `Name` field above `Send Type` selection. Moved `Share` section above `Options` section. Made entire `Options` header div clickable. Adjusted a couple line length issues.
- **send.component.html**: Updated hardcoded string to string resource. Changed `disabled` badge to match icons used in other platforms. Added missing `disabled` check on `Create New Send` button with an empty list.
- **messages.json**: Added missing `Send` string. It won't be translated but should still be a string resource to keep the code tidy.

[Send] Web cleanup

---

src/app/send/add-edit.component.html

> `Current Access Count` input field gives the impression that the value (at some point) could be changed on Firefox and Safari because the action bars are not hidden when `readonly`. 
- **send/add-edit.component.html**: Changed `accessCount` input type from `number` to `text`

[Send] Updated current access input type to text

---

package.json
src/app/send/add-edit.component.html

Added a polyfill for `<type="date">` in Safari
Added date and time fallback inputs for Safari and FF
Wrapped the reused inputs for expiration/deletion dates in a template and supplied where necessary based on their conditions

added date/time fallbacks for safari/ff

---

src/app/send/access.component.html
src/locales/en/messages.json

Clayton asked (& marketing agreed) to remove the 'A' from a Send's creator identifier blurb. 
I also moved that string to messages.json (whoops)

changed send access creator identifier string

---

src/app/send/add-edit.component.html

Updated jslib and adjusted to `<ng-template>` for expirationDate inputs to account for that field not always being required.

Date time fallback fixes

---

src/app/send/access.component.html

> Fix bug where formatted string didn't have necessary data by hiding the `div` when the `creatorIdentifier` is unavailable (send has expired, been disabled, password gated, deleted, etc)
- **access.component.html**: Hide header div when `creatorIdentifier` is `null`

[Send] Hide identifier if unavailable

---

src/app/settings/emergency-access-add-edit.component.html

Currently the Save button in the `emergency-access-add-edit.component` does not show a spinner and disable itself after being clicked. This means the user can click it multiple times and fire off multiple requests to server.
Add `[appApiAction]` on this button and wire up the relevant attributes to `btn.loading`.

Prevent extra clicking of emergency access save button

---

src/locales/en/messages.json
src/services/webPlatformUtils.service.ts

Add more information to the encrypted export warning, so that users know they can't import it into a different account.
This reflects our warning in the [help documentation](https://bitwarden.com/help/article/encrypted-export/).
Aside from the obvious changes in `messages.json`, I also tweaked our `platformUtils` `showDialog` method so that we have the option of using html markup in our modals. (required so that the warning wouldn't be a single blob of text)
Required changes in jslib: https://github.com/bitwarden/jslib/pull/294

Expand encrypted export warning

---

src/app/send/access.component.html

Baby QOL PR I noticed while testing large File type Sends. There's currently no feedback that you're actually downloading anything.
This changes the download button to a spinner to match current BW UI practices. 
We can't use typical download mechanisms currently because we have to decrypt the file stream prior to saving to disk.
* **access.component.html**:

Show spinner when downloading file for Send Accesses

---

src/app/app.module.ts
src/app/send/access.component.html
src/app/vault/send-info.component.html
src/app/vault/send-info.component.ts
src/app/vault/vault.component.html
src/locales/en/messages.json

We should announce our new product loud and proud! This adds a card to the vault which will serve as a place to give a quick description of Send and link to a more info site.
I made this a component so we could show this in other locations if we choose. Right now just in vault
* **app.module.ts**: Register the new angular component
* **send-info.component.html/ts**: Really minimalist angular component that just drops in a card with Send info in it.
* **vault.component.html**: Drop in send info after verify email card, which makes it third in priority (update key, verify email, BW Send)
Waiting on shorter copy from @elizabethbaier.
Looking for other drop-in locations to display this card.

Inform send in vault

---

src/app/vault/send-info.component.html

I accidentally kept the wrong link address in the `how it works` link in Send info card.
This corrects that link to the YouTube how it works video.

Fix how it works link Send Info Card in Vault

---

src/services/webPlatformUtils.service.ts

Safari blocks sharing objectURL data between tabs.
Just use the same tab.
Downloads of PDFs in web should pop open a new tab with the browser's pdf viewer. However, Safari blocks objectURL blob data between tabs. The solution is to just remove the `target="_blank"` attribute from the appended `<a>` tag.
>Note: This code is shared between attachments and Send. This will cause PDF attachments to navigate away from the web vault to display the PDF.
* **webPlatformUtils.service.ts**: Don't append _blank on the `<a>` tag in Safari, it doesn't work.

Open pdf in same tab for Safari

---

src/app/organizations/vault/attachments.component.ts
src/app/services/services.module.ts
src/app/settings/emergency-access-attachments.component.ts
src/app/settings/emergency-access-view.component.ts
src/app/vault/attachments.component.ts
src/locales/en/messages.json

Enable uploading of cipher attachments direct to Azure. Similar PR to #875. Allows for use of new ability to upload directly to Azure or Bitwarden.
* **attachments.component.ts/emergency-access-attachments.component.ts**: Update component DI requirements
* **services.module.ts**: Add file upload service to cipher service
* **emergency-access-view.component.ts**: Set emergency access id. This will be used by the base attachment component to request download using emergency access rather than typical attachment download 
* **messages.json**: update size limit to 500MB

Attachment azure upload blobs

---

src/app/services/event.service.ts
src/app/settings/organizations.component.html
src/app/settings/organizations.component.ts
src/locales/en/messages.json

> Allow user's to enroll/withdraw from the `Password Reset` within an organization.
- **event.service**: Added message support for new event actions
- **organizations.component.html**: Added dropdown options based on the presence of the `ResetPasswordKey`. 
- **organizations.component.ts**: Added `CryptoService` import. Created `toggleResetPasswordEnrollment` function that will encrypt (if necessary) and set the user's `ResetPasswordKey`.  
- **messages.json**: Added necessary strings
- [Jslib Enrollment API](https://github.com/bitwarden/jslib/pull/315)

[Reset Password] Enrollment actions

---

src/app/send/access.component.html
src/app/send/access.component.ts

Fix the following issues on the Send "Hide Email" feature, found during QA:
⚠️ A. When a user has added a password to a send, but has not opted to hide their email, the landing page of the Send will show the "hidden email" banner until the user inputs the password. The sender's email should, it seems, be shown on this page too. (Video Attached) 
⚠️ B. (This is more of a feedback item) When a user clicks the Learn More link in the landing page warning banner, it does not open as a new tab. This is inconsistent with the other links on the page and also could cause problems for access count.

Fix Send Hide Email QA defects

---

src/connectors/webauthn-fallback.ts

The WebAuthn fallback for Firefox incorrectly kept the alert-danger style when initially failing the request and later succeeding. Resolved by resetting the styles.

Fix WebAuthn dialog not resetting on success

---

README.md
src/app/services/services.module.ts
webpack.config.js

It's currently slightly complicated to run the web vault since most browsers requires modifications to properly handle CORS and mixed security. To work-around this I've configured webpack to proxy the api/identity and event requests.
https://localhost:8080/api -> http://localhost:4000
https://localhost:8080/identity -> http://localhost:33656
https://localhost:8080/events -> http://localhost:46273
The `npm run build:prod:watch` command is also updated to properly proxy requests to the production instances.
- **README.md**: Updated to match the new work flow, removed CORS section.
- **src/app/services/services.module.ts**: Changed to always set base url to window.location.origin.
- **webpack.config.js**: Added proxy configuration.

Configure webpack to proxy requests which avoids CORS issues

---

src/app/organizations/vault/ciphers.component.ts

web client changes for: https://app.asana.com/0/1169444489336079/1183168049159854/f
related to bitwarden/jslib#318. Alters Organization cipher view to index and search organization ciphers using the default cipher search algorithm.
* **organizations/vault/ciphers.component.ts**: On load, index the organization ciphers and apply a null filter. Also update Search method to search only organization ciphers.

Create index of cipher orgs and use advanced search with org ciphers

---

src/app/organizations/manage/user-add-edit.component.html
src/app/organizations/manage/user-add-edit.component.ts
src/locales/en/messages.json

> Allow user's with the custom permission type to manage password resets
- **user-add-edit.component.html**: Added checkbox input for toggling permission
- **user-add-edit.component.ts**: update `setRequestPermissions` function to set/update the `manageResetPassword` boolean based on the checkbox state
- **messages.json**: `manageResetPassword` checkbox label added
- [Jslib - Permissions API update](https://github.com/bitwarden/jslib/pull/317)

[Reset Password] Manage Reset Password permission

---

src/app/settings/change-password.component.ts
src/locales/en/messages.json

> When a user change's their password through the settings page, an option to rotate the user's encryption key is offered. When this happens, daisy-chain onto the process and re-enroll **all** `resetPasswordKey` from the calling `orgUser` for each organization.
- **change-password.component.ts**: Added daisy-chained method to rotate encryption key. For all confirmed orgs, re-enroll the `resetPasswordKey` if necessary.

[Reset Password] Rotate encryption key

---

src/app/organizations/manage/people.component.ts
src/app/organizations/manage/user-confirm.component.html
src/app/organizations/manage/user-confirm.component.ts
src/app/tools/weak-passwords-report.component.ts

If you activate the 2FA Policy on your organization, then invite a user which has 2FA activated on their account but they deactivate it after they accept the invitation, you would not be able to confirm them and if you ticked 'Don't ask to verify fingerprint phrase again' before, you would not be shown an error message explaining why.
* **src/app/organizations/manage/people.component.ts**: Catch server errors and display them using the validation service. Now expects a publicKey from the `UserConfirmComponent` instead of delegating the user confirmation to it.
* **src/app/organizations/manage/user-confirm.component.ts**: Moved duplicate code to `people.component.ts`. The `UserConfirmComponent` is now dumber and only handles showing the fingerprint.
* …

Resolve organisation confirm user sometimes not showing errors

---

src/app/services/services.module.ts
webpack.config.js

While testing WebAuthn again I discovered that we hardcode the webvault to localhost:8080 in dev. This is undesired since WebAuthn requires a valid domain name to work. I continued the proxy work in #914 and converted the last services to also be behind the proxy.
* **src/app/services/services.module.ts**: Simplify setting environment variables since dev behaves identical to self hosted.
* **webpack.config.js**: Proxy notifications and portal. Added an allowed host `bitwarden.test` since that's what I use as a test domain.

Extend proxy work

---

src/app/app.component.ts
src/app/send/add-edit.component.ts
src/locales/en/messages.json

Require a user to have verified their email address before being able to create a file Send.
Repos affected:
* server - https://github.com/bitwarden/server/pull/1262
* jslib - https://github.com/bitwarden/jslib/pull/331
* web
* browser - https://github.com/bitwarden/browser/pull/1774
* desktop - https://github.com/bitwarden/desktop/pull/829
* mobile - https://github.com/bitwarden/mobile/pull/1360
I followed the current behaviour for the "premium required" gate. i.e.
* web and desktop - if the user tries to change the Send type to file, create an alert popup with a "learn more" button. After that, the user can go ahead and change the Send type, but will receive the server error message on submit.
* browser - no alert popup, just rely on the server error message
* mobile - alert popup only, …

Require user to verify email to use file Send

---

src/app/send/add-edit.component.ts

Bump jslib and remove `tokenService` from the send `add-edit` component. Required for https://github.com/bitwarden/jslib/pull/344.

Don't use tokenService to manage emailVerified

---

src/app/settings/organization-plans.component.html
src/app/settings/organization-plans.component.ts

The 7 day free trial is only available for new organizations, but we incorrectly state that it is also available when upgrading an existing organization. The template logic is also broken when upgrading, as it displays wording stating that the payment method will be charged after 7 days, but also immediately.
We have discussed extending free trials to existing organizations, but in the meantime I'm pushing this as a quick fix so at least the wording is accurate for the current business logic.

Do not show "free trial" wording if upgrading plan

---

src/app/settings/change-password.component.html

Reported by https://github.com/bitwarden/help/issues/557
Current link: https://help.bitwarden.com/article/change-your-master-password/#rotating-your-accounts-encryption-key
New Link: https://bitwarden.com/help/article/account-encryption-key/#rotate-your-encryption-key

Update rotating encryption key learn more link

---

src/connectors/common-webauthn.ts
src/connectors/webauthn-fallback.ts
src/connectors/webauthn.ts

In the event the server sends invalid WebAuthn data the webauthn processing could error out with no error shown. Resolved by moving the preprocessing inside the try.

 Improve WebAuthn error detection for invalid data

---

src/app/send/add-edit.component.ts
src/services/webPlatformUtils.service.ts

If a file Send takes more than ~5 seconds to upload, and the user does not interact with the page during this time, then the "copy link to clipboard" functionality does not work. This is because Firefox and Chrome consider the page to be inactive and will not let it access the clipboard (presumably to protect users from unexpected page behaviour).
We now show a popup modal if the Send is a file Send; the user wants to copy the link to clipboard; and the upload has taken longer than 4500ms. Unfortunately this does mean that the behaviour will appear different to the user for no particular reason (i.e. whether they get a toast or popup modal with the success message). However, the alternative would be to use the modal more frequently even if it is not required, which is probably a worse UX …

Fix "copy link to clipboard" for large file Sends

---

src/app/vault/add-edit.component.html

When an organization has many collections the add-edit page can get out of hand, which results in the save button disappearing from view. To improve the UX I changed the modal-dialog to be scrollable which better informs the user there is more context as well as keeping the save button always visible.
- **src/app/vault/add-edit.component.html**: Add `modal-dialog-scrollable` to make the modal scrollable.
We should verify it still works nicely on mobile.
https://user-images.githubusercontent.com/137855/117331549-26d94500-ae97-11eb-9401-ef94e03c3e3e.mp4

Change modal-dialog for add-edit cipher to be scrollable

---

src/app/organizations/manage/people.component.html
src/app/organizations/manage/people.component.ts
src/locales/en/messages.json

Currently org administrators needs to manually re-invite each user which requires multiple steps in the UI per user. To streamline this I've replicated the cipher bulk UX for users.
- **src/app/organizations/manage/people.component.html**: Add bulk dropdown, and checkboxes to the users.
- **src/app/organizations/manage/people.component.ts**: Add bulk reinvite handler.
- **src/locales/en/messages.json**: Some new locale for bulk reinvite.
https://user-images.githubusercontent.com/137855/117852541-b3b14380-b287-11eb-99c6-1f05f05ad047.mp4
Depends on https://github.com/bitwarden/jslib/pull/374
https://github.com/bitwarden/server/pull/1316
https://app.asana.com/0/1198901840263430/1200202229721743

Bulk re-invite of org users

---

src/connectors/webauthn-fallback.html
src/connectors/webauthn-fallback.ts
src/connectors/webauthn.html
src/connectors/webauthn.ts

The cloud web vault prevents inline js using CSP rules. Which breaks the WebAuthn buttons. To work-around this I set the `onclick` handler in the script files instead.
- **src/connectors/webauthn(-fallback).html**:  Remove inline `onclick`.
- **src/connectors/webauthn(-fallback).ts**: Set `onclick` handler.

Change WebAuthn connectors to not use inline onclick

---

src/app/vault/groupings.component.html

Uses spaces and dashes as preferred separator in folder names
(instead of just breaking wherever the max width is encountered)
**Current behavior:**
**New behavior:**
**Tested on:**
- Chrome
- Firefox
- Edge

Adds folder word-wrap

---

src/app/tools/import.component.ts
src/services/webPlatformUtils.service.ts

We dont epect to use HTML in the sweetalert title, so switch to `titleText` property.
https://sweetalert2.github.io/#titleText

use swal titletext to avoid XSS

---

src/app/organizations/manage/entity-events.component.ts
src/app/organizations/manage/events.component.html
src/app/organizations/manage/events.component.ts
src/app/services/event.service.ts
src/locales/en/messages.json

Closes https://app.asana.com/0/1199950673439194/1155011472108808/f
Related to bitwarden/jslib#375
Adds the ability to export Organization events to a csv.
* **entity-events.component.ts**: update eventService call to async
* **event.component.html**: Add export button.
* **events.component.ts**: Add events export and update eventService get event info to async
* **event.service.ts**: Add human readable information to event info. This is to support export since we don't want html in our export CSVs. All things we use html for can be searched for by the `shortId` except Policy. Here we need to convert the policyId to a policy type for the organization. This is done through an async call to policyService, which bubbles the whole thing async up to the component level.

Add event export

---

src/app/organizations/manage/people.component.ts

The UI swallows error messages when we remove or re-invite a user into an org. In other methods we explicitly call validationService.showError`, so I added the same logic to these two functions as well.
- **src/app/organizations/manage/people.component.ts**: Add catch handler to remove and reinvite.

Display errors when removing & re-inviting org users

---

src/services/webPlatformUtils.service.ts

Fix #948. Keyboard accessibility of swal2 modals is broken when they pop up over the top of bootstrap modals. For example:
* if you edit a folder (opens a bootstrap modal) and you click delete (opens a swal2 modal to confirm)
* if you edit a login item (bootstrap modal) and you try to regenerate the password (opens a swal2 modal to warn about overwriting existing password)
In these situations, the boostrap modal still has keyboard focus, so:
* screenreaders will not read the swal2 modal
* tab will only cycle focus within the bootstrap modal
* hitting the esc key will close out of the boostrap modal and leave the swal2 modal open
* `webPlatformUtils`: before opening a swal2 dialog, remove `tabindex="-1"` from the bootstrap modal (if any). This lets the swal2 modal take focus. Restore …

Fix accessibility (a11y) on swal2 modals

---

src/connectors/webauthn-fallback.ts

We use `-` in a few of the our locales. These gets replaced to `_` in the filenames and our i18n service. The WebAuthn connector manually loads our locale (to keep the overhead down) and did not do the transformation. Added a `replace('-', '_')` which should resolve the issues and to be on the safe side I also added a fallback to `en` should the locale fail to load.

[WebAuthn] Handle malformed locales

---

src/app/app.module.ts
src/app/organizations/manage/bulk-status.component.html
src/app/organizations/manage/bulk-status.component.ts
src/app/organizations/manage/people.component.html
src/app/organizations/manage/people.component.ts
src/app/organizations/manage/user-confirm.component.ts
src/app/settings/change-password.component.ts
src/app/settings/organizations.component.ts
src/locales/en/messages.json

Confirming multiple users is currently time consuming and involves multiple steps. I decided to change the behavior slightly for all bulk actions so that they show a confirmed status modal with potential errors.
- **src/app/organizations/manage/bulk-status.component.{html,ts}**: Added new component for showing the bulk status.
- **src/app/organizations/manage/people.component.html**: Added confirm selected and the new modal.
- **src/app/organizations/manage/people.component.ts**: Add new bulk confirm api. Changed existing bulk apis to show status modal.
- **src/app/organizations/manage/user-confirm.component.ts**: Change user confirm component to get the publickey as an input.
We should do some quick regression testing on regular confirm and verify bulk confirm works with a few scenarios. …

Bulk confirm

---

src/connectors/webauthn-fallback.ts

Add missing semicolon and enable console.error bypass for tslint that were throwing errors in npm

Fix warnings on webauthn-fallback.ts

---

src/app/services/services.module.ts

As discovered and discussed with @eliykat, in the previous change, the selfhost check was mistakenly taken out of the `services.modules.ts`. This adds the check back in.

adding the self host check back in

---

src/app/organizations/manage/events.component.html
src/app/organizations/manage/events.component.ts
src/app/send/add-edit.component.html

Events export currently exports only the rendered events. It's possible for a large organization to have many events in a reasonable number of clicks/scrolls. A use shouldn't have to load them manually 50 at a time.
This PR eagerly pulls down matching events for export. Events pulled down this way are not rendered or stored beyond the export to avoid UI slowdown.
Exported events are tied to rendered events gathered through a `refresh` button click.
I didn't realize the `btn-submit` class has a nice override when implementing the disable send policy. This override should be used when `Save` is disabled due to disable send policy and set to spin when the form is loading.
* **events.component.html**: define dirtyDates on change. Disable export button in above scenarios
* …

Export all events matching dates

---

src/services/htmlStorage.service.ts

Fix #1005, which was the web version of https://github.com/bitwarden/desktop/issues/894.
The problem is caused by the fact that sets are not serializable, so they get saved as an empty object `{}`, which throws an error when fed to the Set constructor on loading.
Convert sets to arrays before saving in localStorage. Same fix as the desktop version.

Convert sets to arrays before saving to storage

---

src/app/organizations/manage/events.component.html
src/app/organizations/manage/people.component.ts

A few typos in the use of `appApiAction` directive were breaking the responsiveness of the export button. This fixes those typos and restores the intended loading-spinner behavior of the button.
* **events.component.html**: fix directive use
* **people.component.html**: automatic linter fix

Correct appApiAction directive use.

---

src/connectors/webauthn-fallback.ts
src/locales/en/messages.json

Closes #1020 
While an extremely low risk, it's best practice to not use `.innerHTML` for assignment of values dynamically or coming from unknown origins, in this case within a method where the caller may not be known (OOP concept of encapsulation). It would also appear that in this instance this method is only called in exactly 1 place so if we need special handling of HTML in the future here (e.g. this change isn't entirely _correct_) then we can split the message up and handle it accordingly.
* **webauthn-fallback.ts ** - Assign values to `. textContent` instead of `.innerHTML` to remove the possibility of injecting `<script/>` or other XSS techniques.
* **en/messages.json** - Removed the HTML from the translation string. It may not look as pretty on-screen, but for now changes the …

Fix #1020 - XSS via innerHTML property

---

src/app/app.module.ts
src/app/organizations/manage/people.component.ts

When clicking select all in organization people list, it would incorrectly select from all users instead of only the visible users.

Ensure we only select all visible users

---

src/app/organizations/manage/user-add-edit.component.html
src/app/organizations/manage/user-add-edit.component.ts
src/locales/en/messages.json

> For users that are given the `Custom` type, an option to `Manage Password Reset` is available. If this is enabled, make sure that the `Manage Users` permission is also enabled, as its necessary in order to properly reset a user's master password.
- **user-add-edit.component.html**: Added method call that fires during the `(change)` action
- **user-add-edit.component.ts**: Created new `handleDependentPermissions` method that will auto-select the `Manage Users` permission if necessary
- **messages.json**: Added informational string during auto-selection

[Reset Password] Custom Permission pairing

---

.github/workflows/bump-jslib.yml

As discussed in Slack, add a new Github action that lets us bump jslib without having to dive into the command line.
Behaviour:
* must be manually triggered from the "Actions" tab
* if run against master, it will create a new branch, bump jslib on that branch, and submit a PR against master (or update the existing PR if there's already one pending)
* if run against a feature branch, it will bump jslib on that branch and take no further action
* Permissions should be set so that only Bitwarden org members can run it - @joseph-flinn how does this work?
* Currently it's got me marked as the reviewer so that we don't spam the team with review requests while testing. This will need to be changed back to `bitwarden/dept-engineering` once we're happy with it.
* Once it's finalised, add to all …

Add bump-jslib Github action

---

src/app/accounts/accept-emergency.component.ts
src/app/accounts/accept-organization.component.ts
src/app/accounts/login.component.ts
src/app/accounts/two-factor.component.ts
src/app/common/base.accept.component.ts

Since Provider (#1014) adds another `accept` flow, and will require yet another before it's feature complete, I decided to take this moment to refactor the accept components to minimize the required code. While at it, I also replaced the previous states with the more generic `loginRedirect`.
We should do a regression sweep on accept emergency and organization flows.

Refactor accept-organization and accept-emergency

---

.github/workflows/bump-jslib.yml

Improve a few teething problems with the new `bump-jslib` GH action.
* `set-output` only takes a single line input and will truncate any following newlines. (The issue is documented [here](https://github.community/t/set-output-truncates-multiline-strings/16852/3)). This was cutting off the `git log` output. Fixed by moving `git log` into the final step, which is where it's needed anyway, so we don't have to use `set-output` to pass it around.
* improve formatting on the `git log` output when it's appended to a Github PR or comment
* use the more modern bash command substitution syntax: `$(...)`
* change reviewer to the `dept-engineering` team
* rename PR to `[Bot] Bump jslib`. I didn't think "auto" made much sense.

Improve bump-jslib GH action

---

src/services/htmlStorage.service.ts

Fix issue where we aren't awaiting `get` to return its value rather than the promise of one.
FYI, this is a regression item and will be cherry-picked into `rc` upon merger to master. Please evaluate accordingly.
This regression manifests as a failure to lock and failure to decrypt the web vault upon reloading.

Must await to get a value

---

src/scss/plugins.scss

> A recent update to the `angular2-toast` library cause our custom styling to not be applied properly.
- **plugins.scss**: The `toast-container` object is now a `class` and not an `id`. Updated some padding/margin to more closely match the current production toasts style.

[Toast] - BUG - Fixed styles

---

src/app/services/event.service.ts
src/app/settings/emergency-access-view.component.html
src/app/tools/exposed-passwords-report.component.html
src/app/tools/inactive-two-factor-report.component.html
src/app/tools/reused-passwords-report.component.html
src/app/tools/unsecured-websites-report.component.html
src/app/tools/weak-passwords-report.component.html
src/app/vault/bulk-actions.component.html
src/app/vault/bulk-share.component.html
src/app/vault/bulk-share.component.ts
src/app/vault/ciphers.component.html
src/app/vault/share.component.html
src/locales/en/messages.json

The term "Share" is confusing to users because it implies maintaining ownership and control of a cipher while allowing others to access it as well. It also implies the ability to revoke access or to stop sharing -- neither of these things is true.
In addition to the share term being misleading, the [`fa-share-alt`](https://fontawesome.com/v4.7/icon/share-alt) icon implies a forking of the cipher item rather than transferring ownership.
When a cipher is "shared" it is irrevocably taken over by an organization. This occurs for good cryptographic and security reasons. The better solution to this is to revise the communication around "sharing." To that end, this work changes the term "share" to "move to organization" and the icon is changed to …

Redefine cipher "share" to "move to organization"

---

src/locales/en/messages.json

Hey, I noticed that the string doesn't have a capitalized "Send" word.
It a bit messes up with the Crowdin comparing system, as both browser and desktop versions have "Send" capitalized correctly - while mobile and web don't.
I will make a PR on the mobile version too.

maxAccessCountDesc locale string update

---

.github/workflows/qa-deploy.yml
.gitignore

We need an easy, push-button way, for QA to deploy the latest `rc` image of the web client. We are using ArgoCD for a couple of the server services that don't change a bunch set to automatically sync. After thinking through some of the ways to set this up, the best way forward is a workflow that deletes the currently deployed web pod which will then be automatically re-pulled and re-deployed. The ADR can be found [here](https://devops-bitwarden.atlassian.net/l/c/AmW8xfeM).

adding in a workflow to deploy the Web client to the QA environment

---

package-lock.json

The package lock had an ssh git url which was breaking the CI

manually resolving the duo_security package with https instead of ssh

---

.github/workflows/deploy.yml

The recent manual fix of the duo security package didn't fix the problem
This should bypass the problem according to this: https://github.com/readium/r2-testapp-js/issues/10#issuecomment-424522536

fixing the prod deploy workflow error with npm ci

---

src/app/organizations/manage/people.component.ts

> Fix the following: for an organization with no Public/Private keys, the `Manage -> People` component will automatically create/set the key pair on the server. If the user stays within the organization context before a `sync` occurs, returning to the `People` component will result in an infinite loading spinner.
- **people.component.ts**: Force a one time `sync` operation that will replace all of the Organizational data in local storage with the latest from the server.
- This is a bit quick & dirty but is how we currently handle changing organizational data/refreshing the local storage. A potentially cleaner way would be to change the data locally via a successful API response and save those changes to local storage. Unfortunately the only way to update /any/ organizational data is by …

[Reset Password] BUG Org Keys backfill force sync

---

src/app/organizations/manage/people.component.ts

> Fix issue with potentially receiving 401s because `web` didn't gate via permissions like the `server API` does.
- **people.component.ts**: Added permission gate to the conditional surrounding API call to backfill org keys

[Reset Password] BUG Add permission gate to key backfill

---

src/app/accounts/accept-organization.component.ts
src/app/common/base.accept.component.ts

@BlackDex noticed that the organization policies did not show up after the accept-organization refactor in https://github.com/bitwarden/web/pull/1026. As a part of the refactor I switched from using `orgInvitation` and `emergencyAcceptInvitation` to `loginRedirect`. However I failed to notice that `orgInvitation` was used in other places, and I've re-added the state variable. We still use `loginRedirect` to handle the redirects though.
I've opened a ticket in Asana to ensure we QA the original change appropriately.

Fix organization policies not showin up in login/register

---

src/app/tools/password-generator.component.html

**Feature name:**
```
Replace the drop down for password/passphrase option with a radio button choice
```
**Feature Description**
There are only two options in the drop down, would it be better to replace it with a radio button for choice?
- Aids in discoverability: I completely missed the option for a whole year before I thought to click on the option and see what it contains.
- Less number of interactions: It would take 1 less click to get the same result
Community Forum post: https://community.bitwarden.com/t/radio-choice-password-passphrase/30636

chore: radio instead of dropdown (refactor)

---

src/app/components/avatar.component.ts

The current avatar component breaks when it gets an emoji followed by a space. To improve the emoji support I've switched to using unicode aware regex to split the characters. Which seems to be the only way to provide support for compounding unicode. According to https://caniuse.com/mdn-javascript_builtins_regexp_unicode this should have good support.
Depends on https://github.com/bitwarden/jslib/pull/426
Resolves https://github.com/bitwarden/web/issues/838

Add support for emojis in Avatar

---

src/app/settings/payment.component.ts

We had some issues with updating the braintree dependency in #936. Which turned out to be due to the `dropin.js` script being cached both in users browsers and on servers. To avoid this in the future, I've added a cache-busting query parameter similar to how we do it in other places.

Add cache-busting query param to dropin script

---

src/app/oss.module.ts
src/app/send/add-edit.component.html
src/app/send/efflux-dates.component.html
src/app/send/efflux-dates.component.ts

Depends on https://github.com/bitwarden/jslib/pull/428
> Address a regression bug detailed in [Asana](https://app.asana.com/0/1183359552741420/1200508847900795/f) in a way that keeps the feature from regressing in the future and makes the code somewhat easier to live with.
* Implemented the `efflux-dates.component` added in the parent jslib PR
* Refactored the template for these fields to use reactive forms and the component design implemented in jslib
https://github.com/bitwarden/jslib/pull/428
https://github.com/bitwarden/browser/pull/1955
https://github.com/bitwarden/desktop/pull/992

Resolved Safari Date/Time Issues In Send

---

bitwarden_license/src/app/providers/clients/clients.component.ts
src/app/services/event.service.ts
src/locales/en/messages.json

Add events for creating/adding/removing organizations from a provider.
- **bitwarden_license/src/app/providers/clients/clients.component.ts**: Add support for `search` query param.
- **src/app/services/event.service.ts**: Handle the new events. I also made `getShortId` fail gracefully if the value is null. (Should not happen in regular usage, but feels better to show `undefined` than a crashed view.
Depends on: https://github.com/bitwarden/server/pull/1475 & https://github.com/bitwarden/jslib/pull/432

[Provider] Add events for Provider Organizations

---

bitwarden_license/src/app/providers/providers-layout.component.html
bitwarden_license/src/app/providers/providers-layout.component.ts

I had forgotten to re-add the access checks for the tabs in the provider portal.
Resolves https://app.asana.com/0/1198901840263430/1200637533331099

[Provider] Add access checks for tabs

---

bitwarden_license/src/app/main.ts
src/app/main.ts
src/app/polyfills.ts
src/app/settings/add-credit.component.ts
src/app/settings/payment.component.ts
src/services/webPlatformUtils.service.ts
webpack.config.js

In #994, we changed `process.env.ENV` to use `ENV` instead of `NODE_ENV`. This had the side effect of also propagating to other parts where we want to use `NODE_ENV`.
- **app/main.ts**: Angular now only runs in development mode when NODE_ENV==production.
- **webpack.config.js**: Added `NODE_ENV`, and enforce it to be either `production` or `development`.
- **src/services/webPlatformUtils.service.ts**: Changed `isDev` to use `NODE_ENV` to be more consistent with other platforms. And avoid development settings from being exposed in production.
- **src/app/settings/payment.component.ts**: Ensured `ENV` is still used to toggle paypal sandbox.
- **src/app/settings/add-credit.component.ts**: Ensured `ENV` is still used to toggle paypal sandbox. …

Ensure Angular is running as production

---

src/app/accounts/register.component.ts
src/app/accounts/sso.component.ts
src/app/layouts/organization-layout.component.ts
src/app/organizations/manage/policies.component.ts
src/app/services/services.module.ts
src/app/settings/link-sso.component.ts

It was difficult to figure out which urls were used through the application, since there were no central place to store/retrieve them. To resolve this, I refactored the `EnvironmentService` to keep the state private, and instead expose helper functions for retrieving the appropriate urls.
We should verify all api calls, links, etc still works as expected in our different environments. As well as ensuring notification service gets initialized, since the logic no longer happens in `environmentService`.
Depends on:
https://github.com/bitwarden/jslib/pull/435
Related to:
https://app.asana.com/0/1169444489336079/1200631805316488

Use the helper methods in EnvironmentService

---

webpack.config.js

Fixes QA env issue apparently introduced in #1093 
Switch to using `EnvironmentPlugin` to set environment rather than `DefinePlugin`. It appears that the definition of the `process.env` object isn't settings our default values correctly.
I believe the two environment replacements _should_ be identical, but we're seeing issues in qa testing with missing settings. It looks like webpack is replacing the env variable with a variable rather than a string. This plugin just replaces the entire if statement with a boolean

Set env with EnvironmentPlugin

---

.github/workflows/crowdin-sync.yml

Automates the Crowdin translation sync to keep the PR noise down, but increase the ease of use for developers. 
It is currently set up to be manually ran. However, if triggered on a schedule, it will create a single PR and continually update that PR until it is merged in. 
This workflow didn't exist in the default branch, so this has not been tested yet. It must be merged in first

initial trial of automating the crowdin syncing

---

src/app/organizations/manage/events.component.ts

fixes https://app.asana.com/0/0/1200664904812608/f
Manage users is required to list provider users. If this permission is missing we currently fail to load due to an api call failure.
This change skips provider users api call if the user does not have the required permission. the event is then listed as done by the provider name rather than the provider user that did it.

Validate permissions before API calls

---

package-lock.json
package.json

With bitwarden/jslib#441 I added `duo_web_sdk` as a dependency to `jslib/angular`. As jslib/angular is a dependency of this repo, it will pull in it's sub-dependencies of needed. Hence `duo_web_sdk` will still be available.
- **package.json**:  Removed dev-dependency `@types/duo_web_sdk` and git link to `duo_web_sdk`
- **package.lock.json**: Changes after running `npm i`
- **jslib**: Updated submodule to current master

Remove dependency on duo_web_sdk and update jslib

---

bitwarden_license/src/app/providers/setup/setup-provider.component.html

[Bug report](https://app.asana.com/0/1183359552741420/1200652187192756/f)
Currently, the user flow supports an existing Bitwarden user being able to set up a Provider. If a user is not an existing Bitwarden user and attempts to create an account, the page errors out. Create Account should be removed. We will address the non-existing Bitwarden user flow in the next release, given that most of our MSP customers are already using Bitwarden internally. 
* Simply Removed the "Create Account" button from the page. The "Log In" button stretches to fill the empty space. I messed around with making it smaller, but ultimately thought the block behavior looked the best.

Removed create account button from provider setup email

---

src/app/services/event.service.ts

Incorrect null/undefined check was causing errors on event loading.
fixes: https://app.asana.com/0/1153292148278596/1200664904812608/f

Use `!=` for null checks

---

bitwarden_license/src/app/providers/clients/create-organization.component.html
src/app/settings/organization-plans.component.html
src/app/settings/organization-plans.component.ts
src/locales/en/messages.json

fixes: https://app.asana.com/0/1153292148278596/1200645727236036/f
Depends on bitwarden/jslib#442, bitwarden/jslib#444, and bitwarden/server#1488
Add owner invite to provider organization creation.
* **create-organization.component**: require owner invite
* **organization-plans.component**: If `showOwnerInvite` is true, a required field is shown for an owner to invite upon creation.

Add owner email to provider org creation

---

package-lock.json
package.json
src/app/accounts/register.component.ts
src/app/vault/ciphers.component.ts

https://github.com/bitwarden/desktop/pull/1001 and https://github.com/bitwarden/browser/pull/1858 removed the infinite scrolling logic from desktop and browser, in favour of a virtual scroll. Infinite scroll is still required for web, but it doesn't need to live in the jslib base class any more.
This PR moves the paging logic into web.
See https://github.com/bitwarden/jslib/pull/436 for removing this logic from jslib.
Note: tests are failing due to jslib, plus unrelated changes in #1101 and #1104 that haven't been merged yet.

Move ciphers paging logic from jslib to web

---

src/app/services/event.service.ts
src/locales/en/messages.json

Fixes: https://app.asana.com/0/0/1200645727236042/f
Adds vault accessed provider and client organization event types to web event views.
Depends on bitwarden/jslib#448 and bitwarden/server#1496
* **event.service.ts**: Handle vault accessed event types. Organization text just indicates the vault was accessed by the provider. Provider text indicates which vault was accessed as a link to that client organziation
* **messages.json**: Added new event type description strings and corrected examples for several event descriptions.
Depends on bitwarden/jslib#448

Handle vault accessed event types

---

bitwarden_license/src/app/providers/clients/add-organization.component.ts
bitwarden_license/src/app/providers/clients/clients.component.html
bitwarden_license/src/app/providers/clients/clients.component.ts
src/app/settings/organization-plans.component.html
src/app/settings/organization-plans.component.ts
src/locales/en/messages.json

QA Feedback fixes:
* https://app.asana.com/0/0/1200652187192755/f
* https://app.asana.com/0/0/1200645727236036/f
* https://app.asana.com/0/0/1200645727236027/f
* **add-organization.component**: Remove org discovery and rely on passed in orgs. This allows calling pages to determine if the modal should be available at all.
* **clients.component.html**: Do not show gear options if not an admin, the only gear option for now is to remove the client, which required admin permissions.
* **clients.component.ts**: Discover allowed organizations to add to the provider. Do not show the add provider button if none are eligible.
* **organization-plans**: Show the correct owner description for provider client owners. Call toggle on business owned to ensure we select a business-level plan
* …

Provider qa feedback

---

.github/workflows/build.yml
.github/workflows/qa-deploy.yml

Allowing the QA web client to deployed from any branch that has been through a `build` workflow. This change includes a way to manually run a build on a branch and tag it with a custom tag that won't be overwritten on the next build on that branch (`bitwardenqa.azurecr.io/web:master` will always point to the latest build on `master`, but `master-custom` will only be overwritten by manually re-running the build workflow with the custom tag extension `custom`

QA deploy to CI push

---

.github/workflows/deploy.yml

With the version bump to npm version 7, we were experiencing some issues with npm resolving the package source to ssh instead of https. A workaround was presented in https://github.com/npm/cli/issues/2610 to force http in the CI pipeline. That change fixes the issue that happened in the web deploy.

Fixing Automated Web Deploy

---

src/connectors/captcha.ts

fixes: https://app.asana.com/0/0/1200777695141203/f
Android < 10 was OK with redirecting from captcha following a success message posted to parent. However, newer versions are not. These versions were never posting to the callback uri.

Do not call parent if callback given

---

src/app/accounts/two-factor.component.html

Chrome seems to balk at this attribute being added after the fact. It may be a race condition or an intentional block, but adding to the template fixes our missing allow attribute problem.
>Note: this will be cherry picked to `rc`

Set iframe allow on window load

---

.github/workflows/crowdin-sync.yml

The current Crowdin Sync assumes that there are changes and doesn't handle the edge case where there aren't. This change checks for changes before trying to commit and push.

Gracefully handle no Crowdin updates

---

src/app/settings/emergency-access-add-edit.component.html

In the emergency access add-edit component, if the grantee email is invalid, the error toast will show twice.
* The `[appApiAction]` directive was applied twice: once to the `<form>` element, and once to the `<button type="submit">` element. Remove the duplicate directive on the `<button>` element
* There was an `[appApiAction]` directive on the delete button, but it was pointing to an undefined promise. The delete method emits an event for the parent component to handle, so this just seems like erroneous/leftover code that needs to be removed.

Fix bug duplicate error messages in emergency access add-edit

---

bitwarden_license/src/app/providers/setup/setup.component.ts

Adds a redirect which avoids showing the create provider form if the provider is already set up.

Avoid showing provider form if proivder is set up

---

.github/workflows/crowdin-sync.yml

A line was mistakenly removed in the last commit. This adds it back in

Fix broken Crowdin Sync Workflow

---

src/app/services/services.module.ts

In the #1092 I refactored how environment services are loaded, however I missed that I also needed to overwrite the icon service for cloud to ensure the icons are loaded from `icons.bitwarden.net`.
Note: This will be cherry picked to rc.

Overwrite icon service url for prod

---

src/services/i18n.service.ts

With #1079 the AZ language was added. Unfortunately it was set on the first position of the supportedTranslationLocales[]. The first entry is used as a fallback in case the selected locale (browser/system) is not found. This results in users getting for example the login or register site displayed in Azerbaijani.
As can be seen here: https://community.bitwarden.com/t/bitwarden-registration-in-wrong-language/32642

Fixed order of supportedLocales to have 'en' as fallback again

---

src/app/organizations/manage/people.component.ts

In the provider user refactor, the role column disappeared from the organization manage page. The root cause seems to be a typo which references the `providerUserType` instead of `OrganizationUserType`.

 Fix role not being displayed in organization user table

---

.github/workflows/crowdin-sync.yml

- Adding a new coding standard to help identify global variables in a job
- Adding in delay after the crowdin build because crowdin's api is slow. It is labeled "finished" before the download is actually available. Sleeps 15 seconds to wait for their system to catch up.
- Adding a global diff branch for better testing in the future

Crowdin Automation Cleanup

---

src/app/organizations/policies/require-sso.component.ts

Resolves an issue where Require SSO policy could not be enabled with single org policy enabled, the reverse of what it is supposed to be. (Introduced by #1147)
https://app.asana.com/0/inbox/1198901840256133/1200873625261850/1200873689311802

Fix Require SSO Policy prerequisite check

---

bitwarden_license/src/app/providers/clients/clients.component.ts
bitwarden_license/src/app/providers/providers.module.ts
src/app/send/send.component.ts

In #1034 we refactored all modals to use the new `ModalService` which introduced two bugs. Which are resolved in this PR.
1. AddOrganization in Provider Portal generated a NullInjector due to the Provider Module being lazy loaded. This was resolved using a work around where the ProviderModule defines the component factory resolver.
2. SendComponent attempted to use `childComponent` before it was initialized, due to a typo. Changed to use `comp`.
Depends on https://github.com/bitwarden/jslib/pull/471

Fix ModalService refactor bugs

---

bitwarden_license/src/app/providers/clients/clients.component.ts

We had an issue where users didn't have permission to call organizations/:id, which caused an never-ending spinner in the provider portal. To resolve this, I added a check to ensure the user has owner permission of organization, which is required to add an org either way.
Asana: https://app.asana.com/0/1200578627114106/1200880201964177

[Provider] Verify user is owner of organization

---

config/development.json

When running `npm run build:dev:watch` we currently cannot speak with the notification service since it uses websockets. Usually I would solve this by adding `ws: true` to the proxy configuration, but for some reason that crashes webpack on my machine.
Since we recently introduced support for overriding service urls, I instead changed so the application speaks directly to the notification service.

Add notifications to development config

---

src/app/organizations/policies/reset-password.component.html
src/app/organizations/policies/reset-password.component.ts

> The `data` key for the `Reset Password` policy options was accidentally changed during [this](https://github.com/bitwarden/web/pull/1147) component refactor which resulted in any reference to the data to return `false`.
- **reset-password.component.html**: Changed `formControlName` to `autoEnrollEnabled`
- **reset-password.component.ts**: Changed data key from `autoEnroll` to `autoEnrollEnabled`

[Policy] Reset Password data bugfix

---

src/app/organizations/tools/import.component.ts
src/app/tools/import.component.html
src/app/tools/import.component.ts
src/locales/en/messages.json

The Personal Ownership policy prevents users from creating items in their personal vault. However, at the moment it does not prevent a user from _importing_ items into their personal vault.
Update `import.component` template to:
* disable the import form controls if the policy applies (with callout)
* reject any import form submission if the policy applies
Server changes are to follow.

Disable personal imports if Personal Ownership policy applies

---

src/connectors/webauthn.ts

I have a device that is blocking navigation (per chrome dev tools) on the success callback for reasons unknown.  After comparing with the captcha connector (which works flawlessly), the only difference I can find is that captcha doesn't do anything else after `document.location.replace` for mobile.  I'm not sure if this is the culprit but it can't hurt to try.

Possible fix for blocked nav on some devices

---

src/connectors/webauthn.ts

Remove the "WebAuth Error" prefix from WebAuthn error strings

Remove redundant error messaging

---

src/app/settings/change-email.component.html
src/app/settings/change-email.component.ts
src/locales/en/messages.json

The "Change email" panel in Settings lets the user change their account email, but it will not update the email address used for two-factor authentication (if that method is enabled). This is not intuitive:
>  there's a non-zero risk of someone getting locked out of their account because they don't realize 2FA codes are being sent to an old email address, which they might not have access to.
* if the user has the two-factor email method enabled, show a warning callout in the change-email component.
The warning is hidden if the user is not using email 2FA.

Add warning about 2FA when changing account email

---

bitwarden_license/src/app/app.component.ts
bitwarden_license/src/app/app.module.ts
bitwarden_license/src/app/policies/disable-personal-vault-export.component.html
bitwarden_license/src/app/policies/disable-personal-vault-export.component.ts
src/app/organizations/tools/export.component.ts
src/app/tools/export.component.html
src/app/tools/export.component.ts
src/locales/en/messages.json

Implements a *Disable Personal Vault Policy* which lets organizations prevent exports of personal vaults.
- **src/app/tools/export.component.{ts,html}**: Disables input and shows warning if policy is enabled.
- **src/app/organizations/tools/export.component.ts**: Ensure policy is not active for exports of organizations.
Depends on: https://github.com/bitwarden/jslib/pull/482
Asana: https://app.asana.com/0/1198901840263430/1200900473757540, https://app.asana.com/0/1198901840263430/1200900473757539

Add policy for disabling personal vault export

---

src/app/common/base.events.component.ts
src/app/organizations/settings/organization-subscription.component.ts
src/app/settings/change-email.component.ts
src/app/settings/emergency-access-view.component.ts
src/app/vault/bulk-share.component.ts
src/services/htmlStorage.service.ts

Follow up to https://github.com/bitwarden/jslib/pull/490 which removed the `index.ts` files which means we need to use the explicit import paths.

Use explicit import paths

---

bitwarden_license/src/app/policies/maximum-vault-timeout.component.ts
src/locales/en/messages.json

Using a maximum vault timeout of 0 provides a bad user experience.
Resolves https://app.asana.com/0/1198901840263430/1201121327050886

Add validation to ensure maximum vault timeout is larger than 0

---

src/app/organizations/settings/organization-subscription.component.html

Bug fix for #1269 that QA found while testing hotfix. Angular was having trouble with the extra div on multiple rounds of toggling the `*ngIf` attribute.
Fix the issue with repeatedly toggling the form
https://user-images.githubusercontent.com/18214891/139741182-6e86cdd1-52fc-4947-901c-49fd4710584d.mov
Test this form in safari in particular

Fix repeat ng insert on safari

---

src/app/settings/organization-plans.component.html

I made a lazy mistake in PR #1274 in the efforts of getting a screenshot for both types of text that could appear and left in a `!` that shouldn't have been there.
It's for a free trial, not *not* a free trial

Fix free trial text to show at the right time

---

src/connectors/webauthn.ts

Add a fixed-URL for mobile since it does not need to be dynamically passed.
Add a fixed-URL of `bitwarden://webauthn-callback` for mobile redirect.
Ensure that webauthn login works across all clients, especially mobile.

remove callbackUri input for fixed mobile uri

---

src/connectors/sso.ts

It was discovered that a DOM-based XSS vulnerability via a cookie exists in the sso-connector.html page. The page receives the "ssoHandOffMessage" cookie's value and displays it via the innerHTML property. Here, since critical characters (e.g. "<",">") are not encoded at all, arbitrary HTML can be rendered if an attacker can set the "ssoHandOffMessage" cookie, for example, via a subdomain's XSS. Due to the CSP set on this page, it is not possible to execute JavaScript via this issue, however it may still be possible to perform phishing attacks.
Construct the content paragraph in parts and set the paragraph `handOffMessage` with the element's `innerText` property.
Regression test SSO experience via clients to confirm expected behavior persists.

don't use innerHTML for sso handOffMessage

---

src/connectors/duo.ts

Don't allow using domain hosts that are not owned by Duo.
Whitelist `duosecurity.com` and `duofederal.com`.
Regression test mobile to ensure that Duo 2FA still works as expected.

limit duo connector hosts to duo-owned domains

---

bitwarden_license/src/app/organizations/manage/sso.component.html
bitwarden_license/src/app/organizations/manage/sso.component.ts
src/locales/en/messages.json

Before saving Key Connector config, ping the Key Connector URL to make sure it's alive.
* **bitwarden_license/src/app/organizations/manage/sso.component.ts** - ping the Key Connector URL on save, return an error toast if it can't be reached.
Depends on https://github.com/bitwarden/jslib/pull/543.
Try saving the Key Connector config with valid and invalid Key Connector URLs. If the URL is invalid (i.e. Key Connector cannot be reached), you should get an error toast.

[Key Connector] Test that Key Connector URL can be reached before saving

---

src/app/organizations/settings/account.component.ts
src/app/organizations/settings/delete-organization.component.ts
src/app/organizations/settings/organization-subscription.component.html
src/app/organizations/sponsorships/families-for-enterprise-setup.component.ts
src/app/settings/sponsoring-org-row.component.ts

Fixes https://app.asana.com/0/1169444489336079/1201418385615065/f
Organization sponsorship pages display subscription statuses. This is confusing since Stripe doesn't know much about our sponsorship statuses. This PR detects when an organization is sponsored and updates the status to `sponsored`.
Note, this isn't translated, just like the subscription status isn't translated.
This uses the presence a sponsored subscription item to update this status. We need to be really sure that we don't get in a state where we have a sponsored plan and a non-sponsored plan, otherwise this status will be invalid.

Display sponsored status for sponsored org subscription

---

src/app/settings/sponsored-families.component.html
src/app/settings/sponsored-families.component.ts
src/locales/en/messages.json

https://app.asana.com/0/1169444489336079/1201418252130717/f
Friendly name is nice to allow for great flexibility in naming your sponsorships, but it's ultimately unnecessary. The natural way to organize and label these organizations is with the email address the offer is sent to. This PR sets friendly name to the recipient email address and removes the option of changing it from this default

Force sponsorship friendly name to recipient address

---

src/app/organizations/sponsorships/families-for-enterprise-setup.component.html
src/app/organizations/sponsorships/families-for-enterprise-setup.component.ts
src/app/settings/organization-plans.component.ts
src/locales/en/messages.json

Show error page on sponsorship redeem if the token is not going to work. This involved pre-validating the token with new api endpoints.
Messages and view changes related to bad tokens. 
* **families-for-enterprise-setup.component**: Pre validate the sponsorship token to increase likelihood subsequent requests will succeed.
* **organization-plans.component**: linter fix of shadowed variable.
* **messages.json**: new messages
Attempt to bypass the block by re-using a sponsorship link, using a link that have been revoked, the wrong user, etc. In all cases, the page should block use unless the sponsorship will work.
It is still possible to get an error state from the redeem endpoint that isn't caught by the pre-validate token, but it will require usage of the endpoint by a user not entitled …

Add sponsorship pre validate to families redeem page

---

src/app/settings/sponsored-families.component.html
src/locales/en/messages.json

Fixes https://app.asana.com/0/1169444489336079/1201418252130711/f
Correct language around the sponsoring org drop down on families offer page. Previously it was tied to the setup page, which was incorrect. I also made the inputs larger to better match our figma design.

Fix formatting and title of sponsoring org drop down

---

src/app/layouts/organization-layout.component.ts
src/app/organizations/vault/vault.component.ts
src/app/send/send.component.ts
src/app/settings/settings.component.ts

Some components were trying to use the angular implementation of BroadcasterService vs the abstract interface, which caused errors. Related to #1313

Fix components trying to use anglar bradcastservice vs interface

---

src/app/layouts/organization-layout.component.ts

Depends on https://github.com/bitwarden/jslib/pull/580 to fully resolve the bug
Saving organizations throws a blank screen because of a poorly merged import in organization-layout that was moved and isn't currently provided in web.
* Corrected an import
https://user-images.githubusercontent.com/15897251/146115055-e3c52d77-8466-4409-9bba-d13a6d88678c.mov

[bug] Correct bad BroadcasterService import

---

src/app/settings/organizations.component.ts
src/locales/en/messages.json

Fix a string that was not translated in the unlink SSO dialog
- **src/app/settings/organizations.component.ts:** Use i18n to translate missing string
- **src/locales/en/messages.json:** Add missing string

Fix missing translation for unlinking SSO dialog

---

bitwarden_license/src/app/organizations/manage/sso.component.ts
bitwarden_license/src/app/policies/maximum-vault-timeout.component.ts
src/app/organizations/policies/master-password.component.ts
src/app/organizations/policies/password-generator.component.ts
src/app/organizations/policies/reset-password.component.ts
src/app/organizations/policies/send-options.component.ts
src/app/organizations/tools/export.component.ts
src/app/tools/export.component.ts

Rename all occurrences of fb to formBuilder as it can be confusing.
These were the files that needed to be updated:
- **bitwarden_license/src/app/organizations/manage/sso.component.ts**
- **bitwarden_license/src/app/policies/maximum-vault-timeout.component.ts**
- **src/app/organizations/policies/master-password.component.ts**
- **src/app/organizations/policies/password-generator.component.ts**
- **src/app/organizations/policies/reset-password.component.ts**
- **src/app/organizations/policies/send-options.component.ts**
- **src/app/organizations/tools/export.component.ts**
- **src/app/tools/export.component.ts**
No functionality changes, just make sure the forms in organizations -> policies, the organizations export, and vault export forms work as expected.

Tech Debt: Rename fb to formBuilder

---

src/app/services/services.module.ts
src/models/account.ts
src/services/state.service.ts
tsconfig.json

- [Asana Task](https://app.asana.com/0/inbox/1183359552741416/1201592404236978/1201607436480545)
- https://github.com/bitwarden/jslib/pull/593
The storage engine refactor created a bug where dropdown setting values are not defaulting appropriately, most noticeable on web where a vault timeout of "never" should only be allowed for dev, but instead was being applied as a default for all environments. This is addressed in two parts: a jslib PR that sets defaults for locale, theme, and timeout action (as those are the same on each client) and a web PR that extends the account model and sets an appropriate default for vault timeout duration based on environment. 
* Extended StateService and the Account model to set a web-appropriate default for vault timeout and added references to this in …

[bug] Add defaults for vault timeout

---

src/app/services/services.module.ts

**Only reproducable on current master**
I noticed that vault items that had a password reprompt set would not open anymore.
Checking the console also reported an error:
```
ERROR Error: ASSERTION ERROR: Type passed in is not ComponentType, it does not have 'ɵcmp' property.
at throwError (core.umd.js:643:1)
at assertComponentType (core.umd.js:1586:1)
at ComponentFactoryResolver.push../node_modules/@angular/core/__ivy_ngcc__/bundles/core.umd.js.ComponentFactoryResolver.resolveComponentFactory (core.umd.js:25705:1)
at ModalService.resolveComponentFactory (modal.service.ts:88:42)
at DynamicModalComponent.loadChildComponent (dynamic-modal.component.ts:59:48)
at DynamicModalComponent.ngAfterViewInit (dynamic-modal.component.ts:43:10)
at callHook (core.umd.js:2822:1)
at callHooks …
```

Fix items not opening when they have a password reprompt set

---

src/app/vault/add-edit.component.html

helps improve the UX for users with virtual keyboards (mobile devices and tablets
Helps improve the UX for users with virtual keyboards (mobile devices and tablets).
This PR supercedes: bitwarden#661
I wrote about inputmode for CSS Tricks:
https://css-tricks.com/everything-you-ever-wanted-to-know-about-inputmode/#aa-tel
https://css-tricks.com/everything-you-ever-wanted-to-know-about-inputmode/#aa-email

Add Inputmode for tel and email (identities)

---

webpack.config.js

In Webpack 5, `[ext]` contains the `.` character, and should therefore be omitted.

Fix webpack assets using wrong name

---

src/app/app.component.ts

Follow on from the jslib update here, which this client is already using: https://github.com/bitwarden/jslib/pull/616
We moved the call to `keyConnectorService.setConvertAccountRequired` into `syncService`, therefore we can remove it from the message event handler in each client.
Basic regression testing around a user being prompted to convert their account to Key Connector (removing their master password)

Move keyConnectorService call to syncService

---

src/app/settings/options.component.ts

1. When saving on the options page, the confirmation toast has duplicate text in it. It says 'Options updated.' twice within the same toast.
2. In Firefox, the locale dropdown would not have a default setting. In Chrome, the page would always refresh (and then lock the vault) when saving.
- **src/app/settings/options.component.ts** 
-  remove duplicate text
- set the `startingLocale` and `startingTheme` properties properly. These should be set to the same value as `locale` and `theme`, but [this change](https://github.com/bitwarden/web/commit/17ae5ee57c4ecd1ae59b9519b5727bb2546061cb#diff-4c73005a246b799eef390729c9ec4364f3e45723c1bc351a511235caae689ee3R80) replaced the multiple left-hand assignment with null coalescing, which changed the behaviour. However, I think this illustrates that …

Fix various bugs in Options page

---

src/app/services/services.module.ts
src/models/globalState.ts
src/services/htmlStorage.service.ts

https://app.asana.com/0/1201648796371593/1201735234799074
Depends on https://github.com/bitwarden/jslib/pull/646
The default theme for most clients is System, but web uses Light.
We need to extend GlobalState in web to reflect this.
* Extend the GlobalState object and correct services.modules to use the right one for StateService
* Remove the init function from htmlStorageService, it isn't even using the correct data structure and hasn't been doing anything. I think this was dead code even when it was converted to use StateService.

[bug] Extend GlobalState to supply correct default theme

---

bitwarden_license/src/app/organizations/manage/sso.component.html

Currently, due to the multi-client complexity of our platform, we do not _yet_ support IdP Initiated SSO (unsolicited response) in the SAML or OIDC bindings. For SAML, however, our configuration has an option to enable or disable this... which today toggles thin air, unicorn tears, and the color of magical lederhosen (it does nothing basically). This has led to some customer confusion and frustration (understandably).
Will be 🍒 ⛏️ 'd to `rc` if it misses the cut.
- **sso.component.html:** Hide the "Allow Unsolicited Authentication Response" checkbox
This now gets hidden:
Test to ensure SAML configuration can still be loaded and saved.

Hide unsolicited SSO option in config

---

src/connectors/captcha-mobile.html
src/connectors/webauthn-fallback.html

The Captcha and WebAuthn fallback connectors did not use `theme_light` which made them look off if the OS was configured to use dark mode.
Before:
After:

Fix captcha and webauthn-fallback not using theme_light

---

src/abstractions/state.service.ts
src/app/accounts/login.component.ts
src/app/services/services.module.ts
src/models/globalState.ts
src/services/state.service.ts
src/services/stateMigration.service.ts
tsconfig.json

https://app.asana.com/0/1201648796371593/1201750836248439
This will need to be cherry picked into `rc`
RememberEmail should default to true for the web vault, but be toggle-able and persist with the user set setting.
This was broken during the storage refactor work, and needs to be corrected. The current behavior in master has a default of false, but otherwise works.
Since this is a web only setting, I opted to extend the GlobalState model in web to have a new property for `rememberEmail`, and updated the StateService and StateMigration service in web to know about this value.
There is some unrelated maintenance going on here to ensure we have access to extend services, and adding a new `abstractions` folder to the project and `ts.config`. …

[bug] Default rememberEmail to true

---

src/app/organizations/vault/vault.component.html
src/app/send/send.component.html
src/app/vault/ciphers.component.html
src/app/vault/vault.component.html
src/scss/base.scss

> Revert previous margin updates for the buttons within the components below. Add base style class to add margin between icon and text on the button. Merge to `master` and `rc` branches.
- **organizations/vault.component.html**: Reverted exterior margin change
- **send.component.html**: Reverted exterior margin change
- **ciphers.component.html**: Reverted exterior margin change
- **vault.component.html**: Reverted exterior margin change
- **base.scss**: Add rule for buttons with an icon to add a little right margin to properly space the icon/text
- Ensure button spacing looks better than it did before

[Icons] Fix button icon/text margins

---

src/services/state.service.ts

Resolve https://app.asana.com/0/1201804463288267/1201794888247580
We were storing vault data in memory in the web vault to avoid key size limits for storing data in Chrome. This was broken in with the storage restructure, and is put back in this PR. Instead of saving vault data to disk we save it to in memory state.
I tested this by connecting my local web client to the qa cloud vault, and used @Larry-Sussman's test account from the ticket. Vault data loads in as expected.

[bug] Store vault data in memory

---

bitwarden_license/src/app/providers/manage/people.component.html
src/app/settings/emergency-access.component.html

> Fix issue with missing icon due to incorrect reference in the `html` files
- **providers/people.component.html**: `fa-remove` -> `bwi-close` updated to correct reference
- **emergency-access.component.html**: `fa-remove` -> `bwi-close` updated to correct reference
- Make sure the following dropdown menus are correctly showing the `bwi-close` icon

[Icons Bug] fa-remove -> bwi-close

---

src/app/organizations/tools/export.component.ts
src/app/oss.module.ts
src/app/tools/export.component.html
src/locales/en/messages.json

https://app.asana.com/0/1183359552741420/1200074829339233
Depends on https://github.com/bitwarden/jslib/pull/688
Exports are often confusing to users in organizations because there is no indication on screen that a personal export won't include organization items and vice versa. We should add an information panel to this screen noting what exactly is being exported.
- **organization/tools/export.component:** Relocated the `ngOnInit()` logic that grabs the `organizationId` query parameter to above the `super()` call. 
- **oss.module.ts:** Added an import for the `ExportScopeCalloutComponent` added to facilitate this information in `jslib`.
- **export.component.html:** Added an `<app-export-scope-callout>` element if the "Disable Personal Vault Export" policy is not enabled. 
- …

[feature] Implement scope warning for exports

---

bitwarden_license/src/app/organizations/manage/sso.component.html
bitwarden_license/src/app/organizations/manage/sso.component.ts

Remove Artifact binding capabilities from Bitwarden's SSO service for now; they _may_ be added back in the future.
see: https://app.asana.com/0/1169444489336079/1201340159635915/f
see: CSA-6
* **sso.component.html:** 
* **sso.component.ts:** 
* Ensure you can still configure SAML SSO via the web vault and the configuration saves and loads as expected
* Ensure you can still configure OpenID Connect SSO via the web vault and the configuration saves and loads as expected
* See: https://github.com/bitwarden/server/pull/1885
cc: @fschillingeriv 
Because this removes the underlying functionality for the Artifact binding and associated Artifact Endpoint URL configuration in the UI when configuring SAML, this update will need to be made to the documentation when this goes live (likely in March …

CSA-6 Remove artifact binding from SSO config UI

---

src/connectors/captcha.ts
src/connectors/common.ts

This is a fix to correct for broken mobile encoding of captcha data strings with `+`s in url base64.
It will be used to hotfix our handling of captcha for mobile clients.
* **captcha.ts**: use new option to replace ` ` with `+`
* **common.ts**: optionally replace ` ` with `+` for connectors. This should be safe, as proper b64 will never have a space in it, these are only the result of url paramter parsing returning spaces.
captcha testing on current mobile release. hint: czech currently produces a b64 string with a `+` and can be used to test this specific bug.

Fix mobile `+` url encoding issue

---

src/app/accounts/login.component.ts
src/app/app.component.ts

Resolves https://github.com/bitwarden/web/issues/1505
https://app.asana.com/0/1183359552741420/1201900335531015
Enable full width is not persisting across sessions. The value is always there, but the class that needs to be applied is not being applied without manually toggling the setting.
This is happening because `enableFullWidth` is not a global state setting, so it returns false if there isn't an active authenticated session. We need to pivot to setting that value after authentication, which is done in this commit.
https://user-images.githubusercontent.com/15897251/156608222-f136af5f-b4f1-494e-a648-05ffa710a889.mov

[bug] Set full width on login

---

src/app/organizations/settings/delete-organization.component.html
src/app/organizations/settings/delete-organization.component.ts
src/app/organizations/sponsorships/families-for-enterprise-setup.component.ts
src/locales/en/messages.json

https://app.asana.com/0/1153292148278596/1200438690747280/f
This commit updates the organization delete request confirmation warning based on new copy from the product team.
* Add a load toggle to the organization delete modal, as we now have data to collect.
* Adjust how the families for enterprise error state for invalid sponserships connects with the organization delete component. Previously it just sent in a localization key to use for the description, but this commit adds a union type for identifying different delete flows and moves the FFE description localization key into the template with a condition.
* Move the callout on the organization delete component to above the description text.
* Adjust content of the typical organization delete request description based on copy from the …

[feature] Refine content of the organization delete request confirmation warning

---

src/app/app.component.ts

https://app.asana.com/0/1183359552741420/1201900335531015
On https://github.com/bitwarden/web/pull/1516 I moved the `enableFullWidth` check from application startup to on login, citing `enableFullWidth` being an account setting that needed on authenticated account to pull correctly.
This was partially correct, but we still need to also check on application startup for use cases where chrome is closed/reopened with an active session. In that case, we won't have the `enableFullWidth` class applied, because it was never checked, but we also won't ever check since there is no new authentication happening (the reopened session is on the lock screen)
We should check for enableFullWidth in both places, new logins and application startup. This will let each …

[bug] Partially revert #1516

---

src/app/settings/emergency-access-view.component.html

Remove undefined variable that is referenced in a template.
- **src/app/settings/emergency-access-view.component.html** - remove undefined variable.
Best I can tell, this was just copied from another template like this without being updated. The idea of the original code is "if you are not accessing via an org, and the item belongs to an org, show the collections icon". But Emergency Access is always on an individual level, not at an org level, so the first part of the check doesn't apply.
* make sure no regressions (or any changes at all really) in the emergency access view UI.

Remove undefined template variable

---

src/app/layouts/navbar.component.html
src/app/oss-routing.module.ts
src/app/oss.module.ts
src/app/settings/preferences.component.html
src/app/settings/preferences.component.ts
src/app/settings/settings.component.html
src/locales/en/messages.json

> Remove `Settings` from Nav bar
> Change `Options` -> `Preferences` and refactor the similarly named components
> SG-45
- **navbar.component.html**: Removed `Settings` option
- **oss-routing.module.ts**: Update `options` -> `preferences`
- **oss.module.ts**: Update `options` -> `preferences`
- **preferences.component.html**: Update `options` strings -> `preferences` strings
- **preferences.component.ts**: Renamed component and updated string reference
- **settings.component.html**: Update `options` -> `preferences`
- **messages.json**: Updated string names
- Make sure `Settings` option is not available in the nav bar
- Make sure all things `Options` are replaced with `Preferences

[End User Vault Refresh] Nav update and Options -> Preferences

---

src/app/oss-routing.module.ts
src/app/oss.module.ts
src/app/settings/account.component.html
src/app/settings/account.component.ts
src/app/settings/change-kdf.component.html
src/app/settings/change-password.component.html
src/app/settings/change-password.component.ts
src/app/settings/security-keys.component.html
src/app/settings/security-keys.component.ts
src/app/settings/security.component.html
src/app/settings/security.component.ts
src/app/settings/security.module.ts
src/app/settings/settings.component.html
src/app/settings/two-factor-setup.component.html
src/locales/en/messages.json
src/scss/base.scss
src/scss/navigation.scss

> Remove `Change Password` `KDF Encryption` and `API Key` out of the `Account` sub-page
> Remove `Two-Factor Login` sub-page
> Create `Security` sub-page with tabbed header for each of the remove components
> SG-40
- **oss-routing.module.ts**: Added new `Security` sub-page and all child routes
- **oss.module.ts**: Added new `SecurityComponent` and `SecurityKeysComponent`
- **account.component.html**: Removed all components that were migrated to new sub-page
- **account.component.ts**: Removed all pieces of code that were migrated to new sub-page
- **change-kdf.component.html**: Added header to the base component - this is only used in one place
- **change-password.component.html**: Added header to the base component - this is only used in one place
- **security-keys.component.html**: …

[End User Vault Refresh] Security sub-page

---

src/app/providers/providers.component.html
src/app/providers/providers.component.ts
src/app/settings/organizations.component.html
src/app/settings/organizations.component.ts
src/app/vault/vault.component.html
src/app/vault/vault.component.ts

Remove the Organizations and Provider cards from the vault page.
SG-28 and SG-29
These cards reused the `organizations.component` and `providers.component`, which are also used in the settings page. Those components had alternative templates based on an `@Input() vault` property. So instead of removing completely, just delete those parts of the template, and any loading logic in the vault component.
Behold, no cards (except for Verify Email which is staying there for now):

[End User Vault Refresh] Vault - remove Org and Provider cards

---

bitwarden_license/src/app/app.module.ts

In https://github.com/bitwarden/web/pull/1556, I ordered the `ngModules` imports array alphabetically, because that seemed like a nice thing to do.
As it turns out, this matters for route definitions. The effect was that the `bitwarden_license` organization routes were promoted above the `oss-routing.module` routes, and it broke navigation in the org component.
**bitwarden_license/src/app/app.module.ts** - put the `OrganizationsModule` import after `OssRoutingModule`. For good measure, return the order of these imports to their previous ordering as much as possible. Add comment.
Make sure that navigation through organization pages works as expected, also navigation through the app generally.

[EC-115] Restore order of ngModule imports

---

src/app/oss-routing.module.ts

Fixes: https://bitwarden.atlassian.net/browse/PS-141
Add DatePipe to routing module. When creating a send, it opens a popup to the SendComponent. The main app module had it as a provider, but it was not getting it as a provider when routed to. 
- **src/app/oss-routing.module.ts:** Add Date Pipe as provider
Make sure creating sends works

Add DatePipe to providers in routing module

---

package-lock.json

Pull in the work done on https://github.com/bitwarden/jslib/pull/758
Closes https://github.com/bitwarden/web/issues/1548
- **jslib:** Pull in the changes made on https://github.com/bitwarden/jslib/pull/758
- **package-lock.json:** Changes running `npm i` after jslib pull
Create 1pux exports or request ones from @djsmith85 
- Importing any record (not identity) that has a complex email field type should add it as a custom field
- Import complex email field type as email field on identities
- Only save in indentity.email if it is empty, if not save as custom field
- If provider property of email field is filled, save it as custom field

[EC-142] Fix error during import of 1pux containing new email field format

---

src/app/vault/vault.component.html
src/app/vault/vault.component.ts

> Allow vault width to expand to fill card area if no cards are visible (.col-9). If cards are visible, set vault width to current width (.col-6)
> SG-30
- **vault.component.html**: Updated div to conditionally change classes based on card visibility
- **vault.component.ts**: Added helper method `isShowingCards` which will enable the vault width to adjust based on the result
- Maintains current width when cards visible
- Expands vault width when no cards visible

[euvr] Adjust vault width based on card visibility

---

src/app/organizations/sponsorships/accept-family-sponsorship.component.html
src/app/organizations/sponsorships/accept-family-sponsorship.component.ts
src/app/oss-routing.module.ts
src/app/oss.module.ts

Add in an accept-style flow for families for enterprise. This PR doesn't remove the existing param-based navigation for existing offer emails. We can update Server whenever we want to use this flow instead and then determine when we want to remove the parameter-based flow.
- **accept-familiy-sponsorship.component.html**: Just a spinner component. This page immediately redirects to login, so this shouldn't be visible
- **accpet-familiy-sponsorship.comonent.ts**: `BaseAcceptComponent` redirect to families for enterprise setup and login/register (for unauthed sessions)
- **oss-rounting.module**: Add in accept path to routes
- **oss.module**: Register accept family sponsorship comonent
* Validate that redemption of f4e works as expected both with existing url and by navigating to
``` …
```

Use accept flow for families for enterprise

---

src/app/tools/generator.component.html
src/locales/en/messages.json

As mentioned by @patrickhlauke on https://github.com/bitwarden/desktop/issues/1460#issuecomment-1106574103 the fixes on other clients are missing in the web vault.
Currently, the labels for the `A-Z`, `a-z`, `0-9`, `!@#$%^&*` fields in the password generator are difficult to work out/cryptic for assistive technology users: `A-Z` and `a-z` are announced by screen readers exactly the same, and the `!@#$%^&*` is announced as "at number dollar percent and star" (as screen readers will, by default, not announce some of those punctuation marks when presented like that as a nonsensical string in particular). This PR adds new `aria-label` attributes for the checkboxes to provide a more human-understandable accessible name for each of these checkboxes to make them understandable.
This is a port of …

[EC-165] Add aria labels to password gen options

---

src/app/settings/options.component.ts

Resolves an issue where the locale dropdown would default to blank.
Verify the locale dropdown is not empty in private mode. And the content saves correctly.

[PS-381] Fix locale being empty when not configuring a language

---

src/app/modules/vault-filter/components/organization-options.component.html

Using the org filters currently crashes the browser through infinite error messages:
https://user-images.githubusercontent.com/31796059/166624738-388283e4-11eb-4519-943c-c6da6b695f6c.mov
This is caused by `organization-options.component` rendering content before finishing its `load` method. Add an `*ngIf` to delay rendering, plus a spinner so we show something in the meantime.
Here's how it behaves with a simulated 2000ms loading time:
https://user-images.githubusercontent.com/31796059/166624929-0a6708c6-26b6-440d-93ae-609af889cb2c.mov

[SG-224] [EUVR] Fix organization options menu loading crash

---

src/app/organizations/vault/vault.component.ts
src/app/vault/vault.component.ts

The logic for opening ciphers got moved with the #1087. Unfortunately this also meant that the password reprompt logic no longer got triggered. Solved by adding this logic to the new location.
I also noticed that the routing logic for the onClose could be cleaned up slightly.
Verify the reprompt is shown when attempting to view ciphers.

[EC-189] Resolve password reprompt not appearing on linkable cipher

---

src/app/modules/vault/modules/organization-vault/organization-vault.component.ts

Null ciphers signify a _new_ cipher, so no password repromt is required
Fix inability to add ciphers to org vaults.

Check for null cipher in edit

---

src/app/modules/vault-filter/components/organization-filter.component.html
src/scss/vault-filters.scss

https://bitwarden.atlassian.net/jira/software/projects/SG/boards/34?selectedIssue=SG-231
This will be cherry-picked to `rc`
Part of the End User Vault Refresh initiative is to add a "New Organization" link to the bottom of the organization filter options that redirects to the form for creating an organization. This was left out of the initial implementation, and is being added here.
Add the missing link, and use the same styles used by filter buttons.

[fix] Add missing Create Org button to filters

---

src/app/modules/vault/modules/organization-badge/organization-name-badge.component.ts
src/app/organizations/vault/ciphers.component.ts
src/app/vault/ciphers.component.html
src/app/vault/ciphers.component.ts

- Fix text color tending to be too dark for organization badge
- Make organization badge use avatar color for personal vault items
- **src/app/modules/vault/modules/organization-badge/organization-name-badge.component.ts:** 
- Take an input with the profile name to use to calculate the badge color for personal vault items
- Adjust calculation of text color (still using one of the recommended approaches)
- **src/app/organizations/vault/ciphers.component.ts:**
- Get profile name to use for color calculation
- Make sure the badge for individual vault items uses the avatar color
- Make sure text color properly contrasts with badge color

[SG-232 & SG-251] Fix color issues with organization badge

---

src/app/modules/vault-filter/components/organization-options.component.ts

https://bitwarden.atlassian.net/jira/software/projects/SG/boards/34?selectedIssue=SG-255
When clicking on an organization filter a ton of sync requests are sent until requests start being rejected by the server. This is because there is a sync call in organization options, and syncComplete handler in the vault component that triggers it, resulting in a loop of sync -> syncComplete -> sync.
- Remove the sync call from the `OrganizationOptionsComponent`. It is believed this was added in error, and does not appear to be needed here.
Observe that there is no network activity when toggling organization filters: 
https://user-images.githubusercontent.com/15897251/167666815-e28cc643-89a8-4e9a-889d-0326dbdf89b3.mov
- [] I have checked for **linting** errors (`npm run lint`) (required)

[fix] Remove an extra sync call

---

src/app/settings/tax-info.component.ts

We're still getting reports of users being logged out when filling in the payment details on the create organization screen. This is most likely due to a quasi race-condition caused by a tax info call and a create customer call to the Stripe API simultaneously. We previously added a MaxNetworkRetries property in bitwarden/server#1735 but it seems to still be logging out of the web vault. Unfortunately, we haven't been able to recreate this issue.
This change on the web side adds better error handling in an attempt to prevent this logout.

[PS-551] Add error handling to tax info for Stripe rate limiting

---

src/app/layouts/navbar.component.ts
src/app/settings/organization-plans.component.ts

https://bitwarden.atlassian.net/jira/software/projects/SG/boards/34?selectedIssue=SG-240
This will need to be cherry picked to `rc`.
When creating an organization for the first time the navbar is not updating to show the new "Organizations" item. Organizations are checked on init and not synced up after the create event.
I fixed this with messaging, as there isn't a logical grouping between the navbar component and the organization create component right now. This change creates and handles an "organizationCreated" event that checks if the navbar needs to be synced, and syncs if it does.
https://user-images.githubusercontent.com/15897251/167915744-344608cf-624a-47c9-bd55-a66ababd60dc.mov

[fix] Update the navbar when creating an organization for the first time

---

src/app/settings/change-password.component.ts

> Moving the `change-password` component caused me to miss a `super` call during `ngOnInit` to the component's super class. Fixed the password strength meter/submitting the form by adding in the missing method call.
> SG-260
> Will 🍒 ⛏️  to `rc`
- **change-password.component.ts**: added `super` call for `ngOnInit` to make sure necessary variables are properly set

[bug:euvr] Change password init fix

---

bitwarden_license/src/app/organizations/organizations-routing.module.ts

Fix:
> When trying to access the Manage SSO page, an Owner is rejected with a red error toast (permission denied) and redirected back to their vault.
Remove accidental array nesting - `NavigationPermissionsService.getPermissions("manage").concat....` already returns an array, no need to wrap it in another.
**Will be picked to rc**

[SG-264] Fix permission checking when accessing manage SSO

---

src/app/organizations/layouts/organization-layout.component.html
src/app/oss-routing.module.ts

Fix:
> Manage SSO page is missing the navbar and footer
In my organization route changes, I accidentally moved the `OrganizationLayoutComponent` route under the `UserLayoutComponent` route. Then I noticed that I had double navbars and footers, so I removed them from `OrganizationLayoutComponent`. This was all unnecessary, and also broke the routing in the `bitwarden_license` project, which needs to shadow the same routing structure.
Will be picked to `rc`.
Revert these changes by:
* un-nesting the org routes
* re-adding the navbar and footer components

[SG-265] Revert accidental nesting of organization routes

---

src/app/modules/vault-filter/vault-filter.component.ts

https://bitwarden.atlassian.net/jira/software/projects/SG/boards/34?selectedIssue=SG-272
Continuing to mitigate the issues between the EUVR filters work and our sync behavior, the personalOwnershipPolicy only _sometimes_ hides the "My Vault" filter, when it should hide all the time.
This is because we are rechecking orgs after sync but not checking the policies again. I just added some refresh logic for rechecking policies to the same place we recheck orgs.
https://user-images.githubusercontent.com/15897251/168332296-500e0a89-1878-4149-9b95-2d9227483cd2.mov

[fix] Check policies when reloading organizations for filters

---

src/scss/vault-filters.scss

https://bitwarden.atlassian.net/jira/software/projects/SG/boards/34?selectedIssue=SG-274
This will be cherry-picked to rc
Truncated org names are causing a misalignment of the org menu buttons
Keep button alignment in check with a max-width style

[fix] Add max width to vault filter buttons to keep content unified

---

src/app/modules/vault-filter/components/folder-filter.component.html
src/app/modules/vault-filter/components/organization-options.component.ts
src/app/modules/vault/modules/individual-vault/individual-vault.component.ts
src/app/modules/vault/modules/organization-vault/organization-vault.component.ts

[SG-278] Show folders if items from that vault (org) are present
[SG-328] No Folder shows all items
[SG-299] No toast message appears stating user is the only owner when attempting to leave using the 3 dot menu
- **src/app/modules/vault-filter/components/folder-filter.component.html:** Do not hide folders if an org is selected
- **src/app/modules/vault/modules/individual-vault/individual-vault.component.ts:** Fix filter condition for no folder being selected 
- **src/app/modules/vault-filter/components/organization-options.component.ts:** Add error toast if there are exceptions performing organzation options actions (like leavin an org)
https://user-images.githubusercontent.com/8926729/168646681-fdd99944-4607-4743-9107-171920f4d5a6.mov
[SG-278]: …

[SG-16] Fix various small bugs

---

src/app/modules/vault-filter/components/organization-filter.component.html

Fix switcher not appearing for users affected by single org policy
- **src/app/modules/vault-filter/components/organization-filter.component.html:** Use same container for single org policy users, minus the New Organization button. 
User effected by single org policy:

[SG-330] Fix switcher not appearing for users affected by single org policy

---

src/app/organizations/guards/permissions.guard.ts
src/locales/en/messages.json

Resolves EC-203 which prevents non managers from accessing linked organization items.

[EC-203] Add logic for falling back to the users vault

---

src/app/modules/vault-filter/vault-filter.component.ts

**https://bitwarden.atlassian.net/jira/software/projects/SG/boards/34?selectedIssue=SG-333**
Depends on https://github.com/bitwarden/jslib/pull/807
Remove the function implementation of `VaultFiltersComponent.reloadOrganizations()` that was moved to the base class in jslib.

[fix] Remove function implementation that was moved to jslib

---

src/app/modules/vault-filter/components/collection-filter.component.html
src/app/modules/vault-filter/components/folder-filter.component.html
src/app/modules/vault-filter/components/type-filter.component.html

Fix spacing mismatch on vault filters
Add `&nbsp;` before text in types, folders, and collections
| Before     | After |
| ----------- | ----------- |
| ![image](https://user-images.githubusercontent.com/8926729/169056916-f2651196-f4a3-44bb-8ce5-298e0b1c2e26.png) | ![Screen Shot 2022-05-18 at 10 01 27 AM](https://user-images.githubusercontent.com/8926729/169060090-caf18c59-8845-41b9-b621-43a78a886780.png)
|

Make spacing match other rows in vault filter

---

src/app/layouts/footer.component.html
src/app/layouts/frontend-layout.component.html

In the Bitwarden Web Vault, the footer seems to contain an extraneous comma after the year.
removed comma in both footer files
**before**:
**after**:

[PS-502] Remove extraneous comma from web vault footer

---

src/app/modules/vault-filter/vault-filter.component.ts
src/app/settings/billing-sync-key.component.ts

Ignore accented characters in vault searches.
- **src/app/modules/vault-filter/vault-filter.component.ts:** stripped off accented characters from the search input field.
- **src/app/settings/billing-sync-key.component.ts:** removed unused reference

[ps-136] Igonre accented characters in vault search

---

src/app/modules/vault/modules/individual-vault/individual-vault.component.ts

Fix Add item modal not defaulting to the correct item type based on active filter selection
- **src/app/modules/vault/modules/individual-vault/individual-vault.component.ts:** Use activeFilter type and remove `type` variable that is no longer needed because the type is now stored in the `activeFilter` object.
https://user-images.githubusercontent.com/8926729/169889941-0ed3f14d-385a-4074-be48-aad9c51f0978.mov

[SG-344] Fix add item not using correct type

---

src/app/modules/vault-filter/components/organization-filter.component.html
src/scss/vault-filters.scss

There are concerns that the in-line “+” button in the organization filter is not clear enough to understand that means adding an organization, so we are swapping it for the more explicit “+ New Organization“ button that is used for users that do not belong to an org.
**This will be cherry-picked to rc**
- **src/app/modules/vault-filter/components/organization-filter.component.html:** Change in-line plus buttons to "+ New Organization" rows in the organization filter
- **src/scss/vault-filters.scss:** Remove css that is no longer needed
| Case      | Before | After | 
| ----------- | ----------- | ------------|
| New User (same)     |   ![Screen Shot 2022-05-17 at 1 23 17 PM](https://user-images.githubusercontent.com/8926729/170108901-60106281-95c3-4b2c-b382-cc86bbde27b6.png)  | ![Screen …

[SG-345] Switch in-line "+"  add org button to more explicit version

---

src/app/accounts/register.component.html
src/app/send/access.component.html

Properly mark up page titles with the appropriate HTML heading tags. 
/src/app/accounts/register.component.html 
Swapped from `<p>` to `<h1>` HTML tag for the page title.
/src/app/send/access.component.html
Swapped from `<p>` to `<h1>` HTML tag for the page title.

[PS-532] Text is presented as a heading but isn't marked up as a heading semantically

---

src/app/modules/vault-filter/vault-filter.component.ts
src/app/settings/billing-sync-key.component.ts

Reverts bitwarden/web#1690. 
The logic to remove accents from `searchText` has been moved to the `search service` in https://github.com/bitwarden/jslib/pull/812. This PR is no longer needed.

Revert "[ps-136] Igonre accented characters in vault search"

---

src/app/modules/vault-filter/components/collection-filter.component.html

Nested collections could not be expanded/collapsed in the left nav bar.
Closes #1721 
- **src/app/modules/vault-filter/components/collection-filter.component.html:** Replaced non-existant `collapse` method with `toggleCollapse()`
- This will be included in a hotfix for cloud

[PS-779] Fix expanding/collapsing of nested collections

---

src/app/organizations/manage/user-add-edit.component.html

Help center document linked is for the Provider Portal; this modal is for Organization Users. Correcting link to help docs.
The linked Help Article should be set to the article for Organization Users, not for Provider Users, to provide the correct context
- **user-add-edit.component.html:** Updated help center link

Link to correct doc for Org User Types

---

bitwarden_license/src/app/organizations/organizations-routing.module.ts

The permissions for the Manage SSO page are too wide - any manager can access the vault URL (even though the page itself never loads because it’s blocked at the server side). This page should be limited to those where `organization.manageSso` is true, i.e. admins, owners, Manage SSO custom permission.
Note: you have to navigate directly to the URL to find this bug, the button is hidden correctly in the UI.
(This will not be picked to rc. Master only)
Update permissions in the routing guards. The `Permissions` array only requires that 1 of those permissions is met for navigation to be permitted. So:
* keep the "manage" permissions on the parent `ManageComponent` (for consistency with `OssRoutingModule`)
* move `ManageSso` permission down to the `SsoComponent` itself, so that it's always …

[EC-241] Fix Manage SSO permissions

---

crowdin.yml

Crowdin was throwing an error because sr_CS was missing. Now Crowdin should pull Serbian (Cyrillic) and Serbian (Latin)
- [ X] Bug fix

Adding missing code for Serbian Latin
